### ISSUE TITLE
Broker randomly throws out all clients and refuses connections

### ISSUE THREAD

**Issue by timonsku** [eclipse/mosquitto#1023]
I'm running version 1.5.3 on Ubuntu 18.04.
My config looks likes this:
```
listener 1883
listener 9000
protocol websockets
```
Every few hours all clients loose the connection to the broker, even those running on the same machine as the broker and connecting via localhost.
The log doesn't show them disconnecting though except for a few who had a socket error.
The only thing that always seems to happen shortly before everyone gets thrown out is this:
```
1541612275: Client <unknown> has exceeded timeout, disconnecting.
1541612275: Socket error on client <unknown>, disconnecting.
```

A few mobile clients experience repeated socket error other than this unkown client but those happen regularly and the broker continues just fine, whenever this unknown client times out a few seconds later (so it seems) the broker is unreachable and sits idle (not even timing out other clients that were still there but are now unable to connect to the broker).

Any clues? How can a client even be unkown? Is that an anonymous connection?

**Comment by timoline** [comment]
like #986

**Comment by chriswue** [comment]
FWIW - I haven't had the exact same problem but clients would seemingly randomly disconnect when connected to the TCP/TLS port. 1.5.4 has a bunch of SSL fixes (https://github.com/eclipse/mosquitto/commit/8960b1fe29a745cd0ed14ab914833f01adaa5c24) and so far it's looking good. Not sure if that fixes also the websockets problems.

**Comment by PTS93** [comment]
The broker that is acting up does not use auth though.
Weirdly enough the problems stopped as of 2 days ago.
There are three things that can could be the potential cause.
1. Kernel. I downgraded from 4.19.1 to 4.15 the night before.
2. I switched from a fixed IP back to DHCP as DNS was acting up otherwise in our network. I don't see how DNS could have played a role in this as every clients connects via IP but who knows what weird stuff NetworkManager might have done as well.
3. Malicous client not on the network anymore. Two clients that were added to the network the day the issue began have not been online since then. Will test if the issue comes back when we bring those clients back online.

**Comment by ralight** [comment]
I look forward to the update.

FWIW, an <unknown> client comes about if a client is partially removed when being disconnected then fully removed later, it's a quirk that only happens in some situations and I hope to remove it, but isn't something to worry about.

**Comment by ralight** [comment]
DNS could cause some issues if you're bridging from the broker. If you just have incoming clients connecting to an IP then misbehaving DNS shouldn't affect the broker... unless libwebsockets is doing something, which I doubt.

**Comment by PTS93** [comment]
We did encounter the issue again last night unfortunately.
So my suspicion is pointing towards a client again. I enabled verbose logging to see if there is any more valuable information when it happens.

**Comment by sophof** [comment]
Did you ever find out what was causing the issue? I've been having this exact problem for months now and no updates have been able to solve it yet. The log doesn't show me any obvious causes so far.

**Comment by PTS93** [comment]
I think I changed the OS install and the server hardware. After that it was just fine.

**Comment by ralight** [comment]
@sophof Are you able to provide any details on your setup that might help narrow the problem down?

**Comment by sophof** [comment]
I'll give it a try to get more on Friday, currently on holiday. I believe
the log shows some disconnects right before becoming unresponsive.

**Comment by ralight** [comment]
The kind of details that would be useful are what listeners you have, whether you are using encryption or authentication. Where you installed from would be good as well. Are your clients MQTT over TCP, or over WebSockets?

**Comment by sophof** [comment]
Sadly the debug log doesn't show anything interesting, at least to me. My setup is roughly as follows:

I have mosquitto running on a home server that also runs home assistant. I use mqtt exclusively to handle communicaations relevant to home assistant. Currently those are limited to small python programs I've written for my computers, they post their power state (using a will they will be off if the client disconnects). and by sending them messages I can get them to sleep/poweroff/reboot. In addition I'm using mqtt to send my phones location via ssl. So I have both ssl as non-ssl running with acl.

Right, the problem is that the server becomes unresponsive after a day or so. It'll still be running and it'll even show messages like these in the log:
> Sep 01 12:54:10 piet mosquitto[4494]: Received PINGREQ from HTPC
> Sep 01 12:54:10 piet mosquitto[4494]: Sending PINGRESP to HTPC

However, there's no actual published messages arriving. Not from the computers to home assistant or any commands tot he computers. Even using mosquito_sub and mosquito_pub on the server tot test will not result in messages received until I restart the daemon.
In case I do this mosquitto_sub/pub thing, I get the following in the log:
> Sep 01 13:01:10 piet mosquitto[4494]: New connection from ::1 on port 1883.
> Sep 01 13:01:10 piet mosquitto[4494]: New client connected from ::1 as mosqsub|18039-piet (c1, k60, u'admin').
> Sep 01 13:01:10 piet mosquitto[4494]: Sending CONNACK to mosqsub|18039-piet (0, 0)
> Sep 01 13:01:10 piet mosquitto[4494]: Received SUBSCRIBE from mosqsub|18039-piet
> Sep 01 13:01:10 piet mosquitto[4494]:         /test (QoS 0)
> Sep 01 13:01:10 piet mosquitto[4494]: mosqsub|18039-piet 0 /test
> Sep 01 13:01:10 piet mosquitto[4494]: Sending SUBACK to mosqsub|18039-piet
> Sep 01 13:01:14 piet mosquitto[4494]: New connection from ::1 on port 1883.
> Sep 01 13:01:14 piet mosquitto[4494]: New client connected from ::1 as mosqpub|18043-piet (c1, k60, u'admin').
> Sep 01 13:01:14 piet mosquitto[4494]: Sending CONNACK to mosqpub|18043-piet (0, 0)
> Sep 01 13:01:14 piet mosquitto[4494]: Denied PUBLISH from mosqpub|18043-piet (d0, q0, r0, m0, '/test', ... (3 bytes))
> Sep 01 13:01:14 piet mosquitto[4494]: Received DISCONNECT from mosqpub|18043-piet
> Sep 01 13:01:14 piet mosquitto[4494]: Client mosqpub|18043-piet disconnected.
> Sep 01 13:01:17 piet mosquitto[4494]: Socket error on client mosqsub|18039-piet, disconnecting.

So it is denied for some reason, but this is never shown (bad authorisation usually fails silently as well, but not this time strangely enough).

Sadly, it is unclear to me when exactly the server starts failing. There's a few of these "Denied PUBLISH" messages in the log, I expect that it starts there.

Here's all non PING related messages in the log from around the time of the first denied message:

> Aug 31 01:16:12 piet mosquitto[4494]: New connection from 192.168.178.18 on port 1883.
> Aug 31 01:16:12 piet mosquitto[4494]: New client connected from 192.168.178.18 as HAL9000 (c1, k5, u'local').
> Aug 31 01:16:12 piet mosquitto[4494]: Sending CONNACK to HAL9000 (0, 0)
> Aug 31 01:16:12 piet mosquitto[4494]: Denied PUBLISH from HAL9000 (d0, q1, r1, m59, 'computers/hal9000/power/state', ... (2 bytes))
> Aug 31 01:16:12 piet mosquitto[4494]: Sending PUBACK to HAL9000 (Mid: 59)
> Aug 31 01:16:12 piet mosquitto[4494]: Received SUBSCRIBE from HAL9000
> Aug 31 01:16:12 piet mosquitto[4494]:         computers/hal9000/power/command (QoS 1)
> Aug 31 01:16:12 piet mosquitto[4494]: HAL9000 1 computers/hal9000/power/command
> Aug 31 01:16:12 piet mosquitto[4494]: Sending SUBACK to HAL9000
> Aug 31 01:16:18 piet mosquitto[4494]: Client HAL9000 has exceeded timeout, disconnecting.
> Aug 31 01:16:18 piet mosquitto[4494]: Socket error on client HAL9000, disconnecting.

Socket errors happen before this time as well, including messages with this form:

> Sep 01 11:18:35 piet mosquitto[4494]: New connection from ::1 on port 1883.
> Sep 01 11:18:35 piet mosquitto[4494]: Sending CONNACK to ::1 (0, 5)
> Sep 01 11:18:35 piet mosquitto[4494]: Socket error on client <unknown>, disconnecting.

I expected these to be the cause at first, but now I'm not so sure.

**Comment by sophof** [comment]
Ok, sorry, I think I just found the possible cause:

> Aug 31 00:00:01 piet mosquitto[4494]: Reloading config.
> Aug 31 00:00:01 piet mosquitto[4494]: Error: Unable to open pwfile "/etc/mosquitto/passwd".
> Aug 31 00:00:01 piet mosquitto[4494]: Error opening password file "/etc/mosquitto/passwd".
> Aug 31 00:00:01 piet mosquitto[4494]: Client CENSYS disconnected.

**Comment by ralight** [comment]
@sophof great description and fault finding. This is likely a log rotation cron job which causes the config to be reloaded (and hence passwords reloaded). What owner/permission does /etc/mosquitto/passwd have?

**Comment by sophof** [comment]
@ralight It has 600 permissions with root as owner. Strangely enough the issue hasn't happened at all in the past week. I can't remember that ever happening in the past months. The log also doesn't have any 'reloading config' messages, so I'm extra confident that is the issue.

Sadly I haven't been able to find any cron job that relates to mosquitto. Logrotate is in the cron.daily, but I'm unsure how that would trigger a reload?

**Comment by sophof** [comment]
I just noticed that mosquitto is running under the mosquitto user, even though I have it running using systemd (so that I can forward the log to the systemd journal). It seems to work fine though, even though the passwd file is only readable by root?

**Comment by kvoit** [comment]
This seems to happen when the password file is owned by root with no read access to the mosquitto user. It looks like the files are read during startup, before the root privileges are dropped, and then cannot be reread after some reload of the config, which seems to happen at midnight.
I could solve this by changing ownership of the config files to mosquitto. The Debian standard install just lets everybody read the example password file and mosquitto passwd also creates it with 644 permissions.
I think it would be better if mosquitto dropped privileges immediately, or possibly after reading certs, as debugging this was really painful. I did not get the logs that sophof got. Maybe mosquitto_passwd should also create the password file with 600.

**Comment by mosquser** [comment]
See also issue #588, where I lost some time as well until realizing that mosquitto reads the config files with different permissions on startup than on reload.

**Comment by ralight** [comment]
It shouldn't be possible this occurs as of 2.0.
