### ISSUE TITLE
Question, loop_start on windows

### ISSUE THREAD

**Issue by Laro88** [eclipse/mosquitto#1042]
I am struggling to get threaded support to work using the precom

**Comment by Laro88** [comment]
Damn - should not have posted - how to delete a post?

**Comment by Laro88** [comment]
I was writing a question, messed up and posted. (I just read the the loop_thread is disabled in 1.5.4) on windows.

**Comment by ralight** [comment]
Yeah, sorry the windows pthreads library is problematic to distribute because of licensing, so the Windows binaries have been changed to not use them. This is a tradeoff, I think having installers that don't require anything else is a better tradeoff in this case. The old installers were a pain to use.
