### ISSUE TITLE
Unable to connect to mosquitto 1.5.6+ (1.5.5 is fine)

### ISSUE THREAD

**Issue by peterhoeg** [eclipse/mosquitto#1183]
With the following config on NixOS, 1.5.5 is fine, whereas 1.5.6 and 1.5.7 are most definitely not.

The config:
```
acl_file /nix/store/bmxkiliy86bsmsijkc9qwk2xj252d59n-mosquitto.acl
persistence true
allow_anonymous false
bind_address 0.0.0.0
port 1883
password_file /var/lib/mosquitto/passwd

listener 8883 0.0.0.0
cafile /nix/store/gi3mgd7cj8gg4x5sxywbfbwbmp22bmcj-certs-mqtt-server-keys/ca.pem
certfile /nix/store/gi3mgd7cj8gg4x5sxywbfbwbmp22bmcj-certs-mqtt-server-keys/cert.pem
keyfile /nix/store/gi3mgd7cj8gg4x5sxywbfbwbmp22bmcj-certs-mqtt-server-keys/key.pem

listener 8083
protocol websockets
cafile   /nix/store/gi3mgd7cj8gg4x5sxywbfbwbmp22bmcj-certs-mqtt-server-keys/ca.pem
certfile /nix/store/gi3mgd7cj8gg4x5sxywbfbwbmp22bmcj-certs-mqtt-server-keys/cert.pem
keyfile  /nix/store/gi3mgd7cj8gg4x5sxywbfbwbmp22bmcj-certs-mqtt-server-keys/key.pem
```

The error on 1.5.6+ server side is just repeated:
```
Feb 28 21:34:33 elvira mosquitto[173347]: 1551360873: New connection from 10.1.101.22 on port 1883.
Feb 28 21:34:33 elvira mosquitto[173347]: 1551360873: Socket error on client <unknown>, disconnecting.
Feb 28 21:34:34 elvira mosquitto[173347]: 1551360874: New connection from 10.1.101.22 on port 1883.
Feb 28 21:34:34 elvira mosquitto[173347]: 1551360874: Socket error on client <unknown>, disconnecting.
Feb 28 21:34:35 elvira mosquitto[173347]: 1551360875: New connection from 10.1.101.22 on port 1883.
Feb 28 21:34:35 elvira mosquitto[173347]: 1551360875: Socket error on client <unknown>, disconnecting.
```

**Comment by ralight** [comment]
In previous versions, if a client that connected with a username didn't have an ACL explicitly set for them, they were given the ACL of the anonymous users, which was incorrect.

What happens now is that if a client with a username connects and they do not have an ACL assigned to them, meaning that they would be unable to send or receive anything, then they are disconnected. This was not intentional and has been changed in the fixes branch so they are not disconnected, but are still not able to send/receive anything of course.

**Comment by peterhoeg** [comment]
I get the socket error from all users - including those from the ACL file (here's a subset):

```
user rf-1
pattern +/%u/#
pattern homeassistant/+/%u/#

user sw-1
pattern +/%u/#
pattern homeassistant/+/%u/#

user sw-2
pattern +/%u/#
pattern homeassistant/+/%u/#
```

**Comment by ralight** [comment]
None of your users have any ACLs specific to them. The `pattern` is global, you could replace your whole ACL file with:

```
pattern +/%u/#
pattern homeassistant/+/%u/#
```

The real problem is that clients are being disconnected if they do not have ACLs specific to them, even if there are pattern ACLs available as you have. This is fixed in the `fixes` branch and I'm intending to make a release today.

**Comment by peterhoeg** [comment]
Ahh, got it. So since the file is generated, I just made it do this (for now) instead which seems to work:
```
user rf-1
topic readwrite +/rf-1/#
topic readwrite homeassistant/+/rf-1/#

user sw-1
topic readwrite +/sw-1/#
topic readwrite homeassistant/+/sw-1/#
```

**Comment by ralight** [comment]
Yes, that's right.
