### ISSUE TITLE
Update: Modify on exit configuration error

### ISSUE THREAD

**Issue by Tifaifai** [eclipse/mosquitto#1190]
Hi,

In case we have a mosquitto.conf file with additional variable configurations, mosquitto does not launch.
In src/conf.c, the 2005 line warns of the error, but should not kill mosquitto but just inform.
(https://github.com/eclipse/mosquitto/blob/master/src/conf.c#L2005)
I propose to delete the 2006 line.
(https://github.com/eclipse/mosquitto/blob/master/src/conf.c#L2006)
This does not create a safety hole as the auxiliary variables will not be interpreted by mosquitto.

THX

**Comment by ralight** [comment]
I've been thinking about this trying to come up with a reason to back up my feeling that this is a bad idea. Your suggestion is that extra variables do not create a security hole because they will not be interpreted. I agree with you from that angle, but if you look at another angle then it is potentially dangerous. If I make a typo in my config, then at the moment an error occurs and the broker stops. With this change, the broker would carry on with a "broken" config. For example:

```
listener 1883
pasword_file pwfile
```

This would start successfully, but with no authentication, which is a serious error. The user may not spot the log message warning them of the error.

**Comment by Tifaifai** [comment]
Indeed, I now understand your position. 
Maybe create a conf.d folder mechanism with default file and the others file (independent and by theme)

**Comment by ralight** [comment]
Sorry I don't quite understand what you mean.

**Comment by Tifaifai** [comment]
As apache2, with conf.d directory and *.conf.
In mosquitto.conf, add ```IncludeOptional conf.d/*.conf``` for example for other configuration file.

**Comment by ralight** [comment]
Have you seen the `include_dir` option?

**Comment by ralight** [comment]
I'm closing this because the original issue has been addresses, and I believe the second issue was already addressed before it was asked :)
