### ISSUE TITLE
Error: Invalid user 'mosquitto'. Mac Os X Server

### ISSUE THREAD

**Issue by M1ch3L5** [eclipse/mosquitto#1194]
Hello,

I've got the following Problem. I have installed the mosquito via homebrew and i want to run it as root-service as startup of my Computer. If I start it as root, there is the error message: Error: Invalid user 'mosquitto'.
The solution here is to add the user mosquitto. To do so I have to add the user in a terminal, otherwise I have a normal user with login. I don't want this. Can anybody help me. I want to know what privileges, UserIDs, Shells and so on i have to add for the user mosquitto.

Thanks

**Comment by ralight** [comment]
What is happening here is that mosquitto will drop privileges to the mosquitto user if you run as root, so that it is reducing any security risk. The mosquitto user doesn't need to be anything special, on Linux it is typically a system user with a shell of /usr/sbin/nologin or /bin/false, to prevent actual logins occurring.

**Comment by ralight** [comment]
I'm going to close this because I think it is answered, if you need more information please reopen and ask.
