### ISSUE TITLE
TLS error when connecting to a broker in LAN with SSL

### ISSUE THREAD

**Issue by kydoaod** [eclipse/mosquitto#1226]
Hi guys, I am having an issue when I am trying to publish with SSL in my local broker similar with the guy's post here: https://stackoverflow.com/questions/41694772/ssl-error-when-connecting-to-a-mosquitto-broker-from-another-machine

So for my broker setup, here is my mosquitto.conf file:

listener 8883
protocol mqtt
require_certificate true
cafile ca.crt
certfile /path/to/DESKTOP-F0S9ROG.localdomain.crt
keyfile /path/to/DESKTOP-F0S9ROG.localdomain.key

Also in mosquitto_sub side, I have ca.crt, client.crt and client.key
while in mosquitto_pub side, I have ca.crt, client2.crt and client2.key

I have generated the certificates based on this website:
http://rockingdlabs.dunmire.org/exercises-experiments/ssl-client-certs-to-secure-mqtt

Here are some screenshots of whats happening when I tried to publish and subscribe to broker in localhost vs ip address input.

subscriber:
![image](https://user-images.githubusercontent.com/35822186/55972128-7e575780-5cb5-11e9-8fc1-d1def65c652b.png)

publishing to "localhost"
![image](https://user-images.githubusercontent.com/35822186/55972301-d8f0b380-5cb5-11e9-8741-8a74c4dc2202.png)

broker response:
![image](https://user-images.githubusercontent.com/35822186/55972933-13a71b80-5cb7-11e9-85a7-a10a79a9f1d8.png)

publishing to ip address in LAN:
![image](https://user-images.githubusercontent.com/35822186/55973034-4f41e580-5cb7-11e9-9740-c3f12141edc4.png)

broker response:
![image](https://user-images.githubusercontent.com/35822186/55973092-6c76b400-5cb7-11e9-9aa8-c2229e247410.png)

So as you see, its quite problematic when I try to publish from another machine to the machine running subscriber and broker contradicting when I try to publish in localhost. Certificates are the same for localhost and external machine so not sure now why this happens. Is there any fix for this?

**Comment by ralight** [comment]
The most usual problem people have in this sort of situation is that the CommonName (or SubjectAltName) in the certificate doesn't match with the hostname you use when connecting. If your server certificate has CN=localhost, then you would expect it to work when connecting to localhost, but not when using an IP.

The quick check for this is to add `--insecure` to your command line to disable this check. As the name suggests, this is insecure because the client can't verify that the host it is connecting to is correct, so don't use it in production.

If you're still having problems, then try setting `require_certificate false` and not using the client certificates to simplify the situation.

**Comment by ralight** [comment]
This hasn't seen a response for a while, so I'm assuming the previous comment helped and am closing this. If you do still have a problem, please reopen and provide more details.
