### ISSUE TITLE
If the client's datas publish unsuccessfully (because of the network's broken), what will mosquitto do?

### ISSUE THREAD

**Issue by Hapoa** [eclipse/mosquitto#1235]
mosquitto version: 1.5.8

I let the client disconnect with the network for 30 minutes, while it still want to publish datas with qos = 1 to the broker all the time.

~~After 30 minutes, I reconnect the network, and I find that the client will resent these datas that published unsuccessfully in the last 30 minutes, but not all datas will be resent, only **the begining and the end**. It's puzzling! Where's the middle datas??? Just like the below picture,~~

![lALPBE1XX_I3jz3M680B8Q_497_235 png_620x10000q90g](https://user-images.githubusercontent.com/33995130/56451411-1f9d7800-635e-11e9-849b-c4254d16cd83.jpg)

~~And next, I did several tests,~~

![menu saveimg savepath20190420113641](https://user-images.githubusercontent.com/33995130/56451932-a0f60a00-6360-11e9-96e4-f34b52bd8daa.jpg)

~~YES is meaning it resent all datas that published unsuccessfully in the last n seconds/minutes.
NO is meaning the opposite.~~

~~So, two doubts.~~

~~One, why it resent all datas, but don't sent the middle's datas?~~
EDIT: The doubt 1 is my fault, I deleted it. But the doubt 2 is still here as below.
Two, what will mosquitto do if the client's datas publish unsuccessfully (because of the network's broken)?

**Comment by ralight** [comment]
To be honest I don't entirely follow all you're asking.

If a publishing client is disconnected from the broker and the client continues to try to publish, then it depends entirely on the client implementation as to what happens. It may fail immediately on the publish function call, it may queue up messages up to a certain limit and then fail, or queue up the last N messages, or even attempt to queue everything.

In this situation, the broker will not do anything because the client is not connected. Once the client reconnects, it will try to send any queued messages. If there are a lot of messages, the behaviour of both the broker and the client may influence what messages are delivered. The broker only allows a limited quantity of queued messages (by default 100) before new messages are dropped. If the client tries to send qos>0 messages too quickly then it will hit that limit.

A subscribing persistent client that is not connected will have the same situation - any queued messages in the broker are subject to the same 100 message limit.

You can change the queued message limit with the `max_queued_messages` option.

**Comment by Hapoa** [comment]
Thanks for your response, I get it.
