### ISSUE TITLE
Build failure when WITH_TLS=OFF, Linux

### ISSUE THREAD

**Issue by bmparr** [eclipse/mosquitto#1250]
Minor build issue on GNU/Linux:
mkdir build
cd build
cmake -DWITH_TLS:BOOL=OFF ..
make

mosquitto-1.6.1/src/net.c: In function ‘net__socket_listen’:
mosquitto-1.6.1/src/net.c:442:2: error: ‘rc’ undeclared (first use in this function)

ln 421: 'int rc;'  is hidden in #ifdef/#endif

**Comment by ralight** [comment]
Thank you!

Is this option important to you? I've been considering removing the option to compile without TLS support.

**Comment by bmparr** [comment]
Hi Roger,

It only came up with 1.6.1.  One of our target systems is CentOS6.  For
1.6.1, it seams that the version of openssl (1.0.1e) on CentOS6 is a bit
tool old.  On CentOS7, openssl is 1.0.2 and it compiles fine, but on
CentOS6 I see:

../lib/libmosquitto.so.1.6.1: undefined reference to
`SSL_CTX_set_alpn_protos'    (don't have any other versions of openssl
installed)

I didn't see this with mosquitto 1.5.8. We use mosquitto in a closed system
and don't use authentication. I turned TLS off which got me around the
build issue.  I didn't dig beyond getting it to build.  We do plan to phase
out CentOS6 but it will take at least a year. We can always freeze on 1.6.x
for CentOS6.

Regards,
Bruce

**Comment by ralight** [comment]
Thanks for the explanation Bruce. Yes, there isn't support for OpenSSL 1.0.1 because it is not supported by OpenSSL itself. It's fairly straightforward to remove the ALPN code, it doesn't touch much, but I wouldn't want to guarantee there isn't something else that is going to cause problems for you on 1.0.1. There's not a big rush to remove the option of WITH_TLS=no, so I can put that back for a while, probably to 2.0.

**Comment by karlp** [comment]
hijacking a little, but there's quite a few peole on openwrt using the -nossl package variant, as the openssl lib is too big for them, and they're using them in closed internal systems.  You can search for "mosquitto" on https://downloads.openwrt.org/stats/awstats.downloads2.lede-project.org.allextra2.html  (but that's not a long term list just people that download post install, rather than build their own)

**Comment by ralight** [comment]
@karlp That's good to know, thanks.

**Comment by karlp** [comment]
Heading off into the woods, but mbed-tls has become the "goto" "small" tls option.  If there was an mbed-tls option, I could convince people that mosquitto is TLS _ONLY_ but openssl is a hard sell.
