### ISSUE TITLE
C++ library deprecated since 1.6.0 but no alternative...

### ISSUE THREAD

**Issue by cgilles** [eclipse/mosquitto#1267]
Since Mosquitto 1.6.0, the C++ API is tagged as deprecated. Blog list this API to be removed in the future.

In my office, we use this C++ API in favor of low level C API, and it work as expected. MQtt is used as MOM in a large computers infrastructure.

Why to remove this C++ API without to provide an alternative ? Why to remove this code which work fine and is not too large to maintain ?

Note : thanks to provide this library and this broker as open source, it work very well...

Best

**Comment by Laro88** [comment]
We also use the mosquitto c++ and it is a bit annoying that is is deprecated. However since I saw it being deprecated then I have hidden the mosquitto c++ library in a wrapper, and now have the flexibility to switch to paho (c style) or regular mosquitto (c style) and check using infrastructure tests and unit tests.
I can only guess that the deprecation is due to the the threading stuff, and the C library allows focus to stay on the MQTT part of things and not spending time on threading etc.

Paho is not so bad to get up and running using vcpkg and a couple of linker quirks which is fixed with a preprocessor directive. It is the "other candidate" of mine when c++ is dropped and I have to fix.

Cheers.

**Comment by cgilles** [comment]
"the deprecation is due to the the threading stuff"

Do you mean that C++ API is not threading safe ? It's strange because i use it with multi-threaded implementations to stream real time acquisition data in a database through a MOM infrastructure based on Mqtt/Mosquitto (clients and broker), and all work as expected. No crash, no dysfunction.

If you are curious, see below an overview of the framework based on Mqtt used in my office :

https://drive.google.com/open?id=1v4TxxBSBvuImQab9ffCtSqPzKNtteCAi

The data stream cycle is very fast (1 ms), and i write plenty of unit test to be sure that Mosquitto is enough stable and robust to do the job.

I don't know Paho... Can you give more info about ?

Thanks for your feedback

**Comment by Laro88** [comment]
I can only guess / speculate, but at least on Win32 the easy way of subscribing does not work so we manually have to create a thread and guard against a packet receive performing a publish immediately.

Since there is so much backwards compatibility to address then I guess that c++ 0x11 std::thread is not an option and then maintenance on "non MQTT related things" start to take more time than real MQTT development / maintenance.
Take a look here: [eclipse paho](https://www.eclipse.org/paho/)
If you are on windows (as I am) then there seems to be problems with the c++ part of paho, however clean c pahoi works fine.
Take a look at vcpkg on how to get things up and running [vcpkg](https://github.com/Microsoft/vcpkg)
It is a bit scary to let vcpkg take over a lot of the library config and linking locations (I am on VS2015 and VS2017 targeting a complex Win32 legacy application base) however vcpkg has been a great ride so far, but you do loose some control. (The laid back "npm install" feeling for node.js development is there)

I took a look at your framework, looks like you guys have a lot of expensive fun :-)
You should be able to put paho in instead, but if you do youself the favor of creating a shell around your mosquitto c++ usage then you can replace the internals and retest / recertify)
Why did you pick Mqtt when you have a rest interface just above it - just asking - do you need it to distribute manament state to multiple users?

**Comment by cgilles** [comment]
We have few client in windows, but mostly all run under Linux. All my test are done on Linux, as Windows is just a waste of time to develop.

The rest interface is just to catch slow events and display result in web interface.

The real and most important job is to acquire real time data (fast) and to push data in a database quickly.
There are also finite machine states events/states to manage from a top level supervision. all use a MOM, actually in transition state to migrate from RTworks (proprietary) to Mqtt (open source)

The challenge is to be able to manage the most critical case : 50 clients, generate data acquisition frames at the same time, sent to the broker and push to the database. Frames are mostly 5-10 kbytes, but this can be up to 200kb in special cases, send each seconds. 

I currently run qualification tests to see is Mosquitto broker will be able to manage this kind of use.
The client use also Mosquitto implementation, and it's not a problem. Broker is the bottleneck to validate.

**Comment by Laro88** [comment]
Here is a little node.js script that you can use to generate a bit of load on mqtt.
use the mqtt_stresser/t and /s to set the interval in ms and size of array
Don't use mqtt.fx to capture high loads (i crashes on my machine at least) where as mqtt-explorer seems to be able to handle "a lot"
Cheers
```
var mqtt = require('mqtt')


console.log('mqtt_stresser controllable from mqtt')
console.log('mqtt_stresser/t payload interval in ms')
console.log('mqtt_stresser/s payload count of floats to tx')
console.log('mqtt_stresser/q for quit')

var servername = "mqtt://mosquitto"
//var servername = "mqtt://localhost"

var client  = mqtt.connect(servername);


console.log("Conencting to:" + servername)

var t = 20000; //interval ms
var s = 1; //size
var q = 0;
client.publish("mqtt_stresser/t","1000") 
client.publish("mqtt_stresser/s","1")



client.on('connect', function () {
  console.log('connected to:' + servername)
  
  client.subscribe('mqtt_stresser/s', function (err) {
    if (err) {
      console.log("Subscribe error:" + err);
    }
  })
  client.subscribe('mqtt_stresser/t', function (err) {
    if (err) {
      console.log("Subscribe error:" + err);
    }
  })
  client.subscribe('mqtt_stresser/q', function (err) {
    if (err) {
      console.log("Subscribe error:" + err);
    }
  })
  
  loop(); //start the loop
})
 
client.on('message', function (topic, payload) {
  // message is Buffer
  console.log("message received, topic:" + payload + " payload:" + payload.toString())
  
  if(topic == 'mqtt_stresser/t'){
	  t = payload * 1;
	  console.log('t set to:' + t)
  }
  else if(topic == 'mqtt_stresser/s'){
	  s = payload * 1;
	  console.log('s set to:' + s)
  }
  else if(topic == 'mqtt_stresser/q'){
	  q = 1;
	  console.log('q received, quitting')
  }
  
  else{
	  console.log('Unhandled topic:' + topic);
  }
})


function loop(){
	if(q == 0){
		var arr = []
		for(var ptr=0;ptr<s;ptr++){
			arr[ptr]=Math.random()
		}
		var arrAsStr = arr.toString();
		console.log("Creating an array of size:" + s + " content:" + arrAsStr);
		client.publish("mqtt_stresser/data",arrAsStr);
		setTimeout(loop, t);
	}
	else{
		console.log('mqtt_stresser terminating')
		process.exit()
	}
}
```

**Comment by cgilles** [comment]
Thanks for the feedback about the stressing test tool.
In fact we write specific unit tests with in C++ with Qt and Mosquitto API to run performance test on the broker. We install a cubical with many computer connected to a dedicated network and plenty of client computers, sending data frame through Mqtt to a client receiving frame and store data to a local database. Each steps of sending and receiving data time are evaluated, as also the network statistics passing through an remote admin Gb switch.
The frame data are specific format compressed and simulated with an home maid code. Like this we are sure to test in real condition.
I will give feedback when first results as graphs will be computed.

**Comment by ralight** [comment]
The C++ wrapper is no longer deprecated and is up to date with the C library for the 2.1 release, so I am closing this issue.
