### ISSUE TITLE
Subscribe ACL check is bypassed if the client is using non-MQTTv3.1.1 ?

### ISSUE THREAD

**Issue by samsonchen** [eclipse/mosquitto#1318]
The subscribe ACL check gets bypassed if the client is not using v3.1.1 protocol to connect? I made a simple-and-quick fix to force all the subscribers to use only the v3.1.1, but maybe this is not the right way to handle the v5 protocol. I just wonder why? Here is my quick fix: https://github.com/tracmo/mosquitto/blob/v1.6.3.no_nonMqtt311/src/handle_subscribe.c

**Comment by ralight** [comment]
The subscribe acl check is not run for MQTT v3.1 clients only, because 3.1 doesn't provide a mechanism to say that a subscription was denied.

It shouldn't actually matter, because the acl check is just about making the subscription, not about receiving messages. The "publish read" acl check will catch the messages later on.

**Comment by samsonchen** [comment]
Thanks for the answer. I will close this issue.
