### ISSUE TITLE
util_mosq.c getrandom pre kernel 3.17

### ISSUE THREAD

**Issue by nickper** [eclipse/mosquitto#1403]
I was debugging a problem where i got a unknown error as return when i tried to connect. And it uses a systemcall at line 330, which returns -1 function not initialised.
```C
#elif defined(HAVE_GETRANDOM)
	if(getrandom(bytes, count, 0) == count){
		rc = MOSQ_ERR_SUCCESS;
	}
```

i couldn't anything about which kernel is supported and apparently this is supported from kernel 3.17 while mine is kernel 3.10. 
I had to create a function which get these random numbers from the /dev/urandom directly..

i want to propose 2 thinks
- a better error message when getrandom is resolved with -1 where instead of "unknown error" the error states as "function not initialised" or something similar.
- a fallback when getrandom returns -1 and the funtion not initialised error. by directly reading from the /dev/urandom file.

I would gladly hear what your oppions are about this.

**Comment by ralight** [comment]
I feel like you're making life difficult here :) You've got kernel 3.10 from 2013, glibc 2.25 or later from 2017, plus you're not using TLS. I hope you'll agree that a 2013 kernel with 2017 glibc is not a situation that most people are likely to come across.

Your options are to start using TLS, manually disable the HAVE_GETRANDOM check, use a glibc version older than 2.25, use a kernel version newer than 3.17.

I don't really want to put in extra code to cover this case, because I think it only affects a vanishingly small set of circumstances. Are you happy following one of the suggestions above?

**Comment by nickper** [comment]
True, it is only a small set of circumstances. And unfortunatly i didn't design my build and work environment. 
Even then i found it important to at least notify it.
