### ISSUE TITLE
Using native threads on Windows

### ISSUE THREAD

**Issue by laudrup** [eclipse/mosquitto#1509]
Currently mosquitto requires pthread for Windows to use threading on Windows.

Is there any reason why this library doesn't use some simple wrappers for the threading functionality it requires so it can use native threads on both Posix and Windows?

It seems like it should be relatively simple to implement and I will be happy to do so through a pull request, just want to know if there's any reason why this hasn't been done before I spent time on it.

Sorry if this is more of a question than an actual issue. Don't know if there's a better way to ask questions like this on github.

**Comment by ralight** [comment]
Libmosquitto doesn't absolutely rely on pthreads for Windows, it just needs an implementation of the pthreads API, so you are quite correct that you could write a simple wrapper.

There is a BSD licensed implementation that attpts what you suggest here: http://locklessinc.com/articles/pthreads_on_windows/

**Comment by laudrup** [comment]
Thanks for your reply.

So would you be interested in a pull request for a wrapper that uses native threads on Windows?

**Comment by crazydef** [comment]
Hi,

I've just started looking into integrating mosquitto into our codebase, and this is a major blocker for us (who writes single threaded applications these days?).

What's the status of this?  (I see your pull request is failing on Mac for seemingly unrelated reasons - is anyone looking into that?  Can that be worked around?)

**Comment by laudrup** [comment]
Hi @crazydef,

The master branch and develop branch is indeed currently failing so that is not related to my pull request at all.

Not sure what the status of this pull request is. I think the first thing that should be fixed is the master and develop branch. Before that no pull requests can really be merged (that would defeat the whole point of having CI checks IMO).

There doesn't seem to be much development on this project at all, not sure what to make of that...

**Comment by crazydef** [comment]
Well, two months since the last push is definitely better than some github projects I've seen recently.  :)

But either way, I ended up using the single-threaded version of mosquitto and marshalled all incoming and outgoing messages through my own message queues and have a worker thread that calls into mosquitto manually to pump its message loop and get things moving.

Ironically, it turned out there are other parts of our system that also needed things to happen on specific threads, so doing it this way actually turned out a bit better for me in the end.  Barring any major bugs or issues though, I don't think I'll be looking at this part of the system again anytime soon.  :)

**Comment by karlp** [comment]
re activity, perhaps look at https://github.com/eclipse/mosquitto/commits/fixes instead. even two months would just mean "stable" not "this project is dead"

**Comment by laudrup** [comment]
@karlp Reading my comment again, I can understand why it sounds like I might have declared this project dead, sorry about that.

I'll just leave my pull request as it is for now. Hopefully someone will have a look at it at some point.

**Comment by ralight** [comment]
This has now been addressed for the 2.1 release.
