### ISSUE TITLE
Mosquitto doesn't send stored QoS 1/2 messages when a persistent client subscribed with QoS 0 connects

### ISSUE THREAD

**Issue by abforce** [eclipse/mosquitto#1511]
The persistent client that subscribes to `foo` with QoS 0:
```
mosquitto_sub -i abc -u abc -P abc -h <my_host> -p 1883 -q 0 -c -t foo
```
If I publish a message with QoS > 0 while the client is offline (the session is previously created, it's not a new client id), when it comes back online the message isn't delivered. This is a bug according to the MQTT spec.

version: mosquitto 1.4.8 (also tested with the latest version 1.6.7, the problem still exists)

**Comment by ralight** [comment]
When you subscribe with QoS 0, it effectively doesn't matter what the QoS of the message was originally, for you it will always be QoS 0.

The v5 spec states (the intention is the same in the v3.1.1 spec):

> The Session State in the Server consists of:
> ...
> * QoS 1 and QoS 2 messages pending transmission to the Client and OPTIONALLY QoS 0 messages pending transmission to the Client.
> 
> ...

So you see that with a QoS 0 subscription, there will never be any QoS 1 or QoS 2 messages pending transmission to the client, they will have been changed to QoS 0.

If you want QoS 0 queueing in Mosquitto, add `queue_qos0_messages true` to your config.

**Comment by abforce** [comment]
No, I think you've misunderstood the problem. I'm not publishing with QoS 0, the message is published with QoS>0, but some clients wish to receive it with QoS 0, I mean the clients need to *receive* the message but don't want to respond with a PUBACK and keep the broker busy.

**Comment by abforce** [comment]
No, I think you've misunderstood the problem. I'm not publishing with QoS 0, the message is published with QoS>0, but some clients wish to receive it with QoS 0, I mean the clients need to *receive* the message but don't want to respond with a PUBACK and keep the broker busy.

**Comment by ralight** [comment]
I do understand. The QoS of the message being published from the client to the broker is irrelevant, because you have subscribed with QoS 0. At the point of attempted delivery to the subscribing client, the server says "I have received a message with QoS 1 or 2. This client only wants to receive QoS 0 messages for this subscription, so when I am preparing to deliver that message I will first downgrade the QoS to 0. Secondly, I see that the client is not currently connected, so I must decide whether to queue the message for later delivery or not. As the outgoing message QoS is 0, I should discard the message".

If you want your clients that subscribe with QoS 0 to receive messages when they are offline, you must set `queue_qos0_messages true` in your configuration. The only other way would be to subscribe with QoS>0. 

This is not a protocol violation, it working exactly as it should.

**Comment by abforce** [comment]
Okay, thank you for the clarification. :)

**Comment by abforce** [comment]
@ralight  I just tested with `queue_qos0_messages true`, Mosquitto only sends messages for those clients who have been offline for a while, but doesn't send messages for clients disconnected recently within a few minutes. I think for clients recently disconnected, the broker thinks they are online and tries to send them the messages but a socket IO error occurs and since QoS is 0  the broker discards the messages. Is it right?
