### ISSUE TITLE
 Port to haisi linux

### ISSUE THREAD

**Issue by without1022** [eclipse/mosquitto#1605]
When I tried to port it to HiSilicon Linux, I encountered the following problem. I can compile the src or lib directory separately, but this error will occur when compiling the client directory. Can you help answer it?
![33B66BB5-6206-4dd1-87DC-A1BDCB14C132](https://user-images.githubusercontent.com/30370274/74813838-eee8ef00-5330-11ea-876c-8c242d7423f0.png)

**Comment by karlp** [comment]
this is not a mosquitto problem, this is a problem in your buildroot.  You don't have openssl.  You can either disable ssl, or get it in your buildroot, but it's not a mosquitto problem.

**Comment by without1022** [comment]
when I add `LDFLAGS += -lssl -lcrypto`  into config.mk.This problem is resloved.but why?Why this problem does not appear when I compile the src directory？

**Comment by ralight** [comment]
When you compile and link the broker (src directory), it links directly against libssl and libcrypto. The same is true with you compile and link the client library (lib directory). When compiling the command line clients (client directory), the clients are not explicitly linked against openssl. They don't need to be, because that is linked by the client library. What you seem to have is the linker not being aware that the linked client library already knows how to load the openssl libraries. It is a little annoying for you, but I do think it is your linker that is at fault.

**Comment by without1022** [comment]
Thank you very much for your help
