### ISSUE TITLE
Race conditions with disconnecting and mosquitto loop

### ISSUE THREAD

**Issue by jcavar** [eclipse/mosquitto#165]
Hi,
It seems there is a race condition issue with mosquitto loop and disconnecting.
So `mosquitto_loop_forever` calls `mosquitto_loop` without any mutexes. Then `mosquitto_loop` calls `mosquitto__socket_connect_tls` which eventually calls `SSL_connect(mosq->ssl)`. If `_mosquitto_socket_close` is called before, this results in EXC_BAD_ACCESS on `mosq->ssl`. 

We were able to reproduce this by calling connect/disconnect in a loop on different threads.
Are we missing something here, or this is really bug?

**Comment by jcavar** [comment]
My understanding is that `mosquitto_loop` should not be called before first locking `state_mutex`?

**Comment by ralight** [comment]
It's quite possible this is the case. Could you provide the example code you've put together? Did you use `mosquitto_threaded_set()` if you're using your own threads?

I think that calling `mosquitto_loop()` with a locked `state_mutex` would make the state mutex basically pointless, so it may need a different approach.

**Comment by jcavar** [comment]
Thanks for fast reply! It seems that calling `mosquitto_threaded_set()` fixed our problem. I am not sure i understand what this exactly does, but is there a reason why this is not enabled by default when compiled with WITH_THREADING?

**Comment by ralight** [comment]
WITH_THREADING just compiles in thread support or not, but that doesn't mean you actually need to use threads.

For the single threaded case, when you call e.g. `mosquitto_publish()` it will queue the message for delivery and then immediately call `write()` to try and send the message. This means in many cases you will have already sent the message before calling `mosquitto_loop()`. I believe this to be an advantage for single threaded operation.

When using multiple threads, this behaviour is not wanted because the network processing will normally be handled by a separate thread. If we carried on allowing `mosquitto_publish()` to attempt writing to the network then there would be greater need for locking between the threads and for no real advantage. When you call `mosquitto_loop_start()`, the client knows that there are multiple threads and hence does not use the single threaded optimisation. If you use your own threads, it has no way of knowing this and so you have to tell it separately.

I hope that makes some sense.

**Comment by jcavar** [comment]
I see your point, but when you don't use threads you could have compiled without them, right?
Anyway, I will close this issue, because we don't have problem anymore. Thanks!

**Comment by ralight** [comment]
Yes you could have, but in practice I bet most people will use precompiled binaries that support everything.

**Comment by jcavar** [comment]
Yes, but then I don't see why WITH_THREADING is an option? You can turn it off/on on application level anyway.

**Comment by ralight** [comment]
That's for the situations where pthreads isn't available, or where it isn't desirable. It gives the end user choice, either they get the full library with everything in that can work well in single or multiple threaded mode, or they can produce a different version of the library which only has the features compiled in that they want.

**Comment by jcavar** [comment]
I see. That makes sense. Thanks 👍
