### ISSUE TITLE
ESP client secure connection which option is better

### ISSUE THREAD

**Issue by maminis** [eclipse/mosquitto#1655]
Attention Mr. @ralight  ,

Hope you are well. I have some questions, kindly answer my questions below.

Below my mosquitto broker configuration file installed on centos 7 server.

__________Start mosquitto.conf__________________
```
persistence true
allow_anonymous false
password_file /etc/mosquitto/passwordfile
clientid_prefixes clientid-

#MQTT (mqtt)
listener 1883
protocol mqtt

#WebSocket (ws)
listener 9001
protocol websockets

#MQTT_Secure (mqtts) (Option 1)
listener 8883
cafile /etc/letsencrypt/live/domain.com/fullchain.pem
certfile /etc/letsencrypt/live/domain.com/cert.pem
keyfile /etc/letsencrypt/live/domain.com/privkey.pem

#MQTT_Secure (mqtts) (Option 2)
listener 8883
cafile /etc/letsencrypt/live/domain.com/fullchain.pem
certfile /etc/letsencrypt/live/domain.com/cert.pem
keyfile /etc/letsencrypt/live/domain.com/privkey.pem
require_certificate true
tls_version tlsv1.2
```
__________END mosquitto.conf__________________

___________In case of openssl self-signed certificate___________
```
#MQTT_Secure (mqtts) (Option 2)
listener 8883
cafile /etc/mosquitto/tls/ca.crt
certfile /etc/mosquitto/tls/server.crt
keyfile /etc/mosquitto/tls/server.key
require_certificate true
tls_version tlsv1.2
```
#______________________

My questions in case of

1. Option 1 - If I use only mqtts port 8883 on the esp client side to connect broker then is this connection method will be fully secure?
Option 1 connection example for ESP32 Firmware + WiFiClientSecure library
```
[
Broker: mqtt.domain.com
Port: 8883
user: abcd
Passwrod: 1234
Client Id: clientid-esp32
]
```

2. Option 2 - If I use mqtts port 8883  with certificate files or Hash code to connect broker then is this connection method is more secure than option 1?
Option 2 connection example for ESP32 Firmware + WiFiClientSecure library
```
[
Broker: mqtt.domain.com
Port: 8883
user: abcd
Passwrod: 1234
Client Id: clientid-esp32
ca.crt SHA1 Fingerprint: B3 2C 4D 48 2B 15 F1 52 62 7A 46 23 DE A4 20 1B 1E 0F 38 95
OR
ca.crt...only
OR
ca.crt...
client.crt...
client.key...
]
```
What is the right option to secure client side connection i know both are encrypted connection. I want to use into the esp32 firmware to secure connection with the broker.
**Option 1 and Option 2 are two secure connection method for a client to connect broker but which option is better to use?**

3. What is different between self-signed SSL and Paid service SSL certificate used to secure mosquitto broker only for client server connection.

Sorry for my poor english...

Best regards

**Comment by ralight** [comment]
I think the summary of your question is "should I use client certificates when I am using TLS encryption". That's what I'm going to answer, if I've got that wrong please correct me.

Using TLS means your communication is encrypted. Using client certificates or not doesn't change that.

Using server only certificates means that your client can (if you do it properly) verify that the server it is connecting to is trusted, and is the correct server. It uses the certificate authority certificate to determine if the server certificate is trusted, and then must also check whether the name in the certificate matches the hostname it is trying to connect to. If either of these checks fail, the client does not connect.

If you require client certificates then the client must also have its own certificate. The server must then also have a certificate authority certificate that has signed the client certificates. If the server does not trust the client certificate, the client will not be able to connect. This allows the client certificate to be used as an authentication step.

Using client certificates means it is potentially more difficult for unauthorised clients to connect to your server, but it has a significant overhead in terms of dealing with the certificate infrastructure. You should think very carefully before committing to it.

A paid for SSL certificate will have widely used certificate authority support. For web browsers this is important, because without the CA certificate being trusted by the browser the connection will be viewed as untrusted. This applies to self signed certificates as well. If you are making an MQTT system where clients only ever connect to your server, they are only using MQTT (no websockets), and you are providing the certificates yourself, then using a self signed certificate should be ok because you can install the self signed certificate on all your client devices.

**Comment by ralight** [comment]
I think this question has been dealt with, so I'm closing it. If you disagree, please reopen and add more details.
