### ISSUE TITLE
SSL/TLS procedure

### ISSUE THREAD

**Issue by EdoZullo** [eclipse/mosquitto#1672]
Hi, i'm trying to configure ssl on mqtt unsuccessfully, follow a lot of different tutorial but it doesn't work anything.
Which is the correct procedure to follow to generate files?
I already have a certificate file (attach image) can i use these files?
![Schermata 2020-05-04 alle 00 50 43](https://user-images.githubusercontent.com/38581202/80927926-54317580-8da1-11ea-8eb2-cf5179193e3c.png)

Thank you.

**Comment by ptjm** [comment]
Minimal config to use the files above:

port 8883
cafile /some/directory    # please see my note below
certfile fullchain.pem
keyfile privkey.pem

You have to have either a cafile or capath entry. If you don't plan to do authentication using peer certificates, you can use some empty directory for the capath. Otherwise, you need either a file with the CA certificates you want to use to authenticate your clients, or a directory with them set up following the manner of openssl CA directories.

**Comment by EdoZullo** [comment]
Thanks for the replay.
Settings this and everything works!
cafile chain.pem
capath directory that contain .pem file
certfile fullchain.pem
keyfile privkey.pem
