### ISSUE TITLE
How to set limit value of data queues?

### ISSUE THREAD

**Issue by itadakimatsu97** [eclipse/mosquitto#1676]
Hi all,

I am new in mosquitto data queues.
As i know the config file has <memory_limit> value to limit number of heap memory bytes that the broker will allocate.
So i have 2 questions:
- How does it affect to mosquitto.db file?
- Is there any way to set mosquitto.db with limited size? example 1mb, 5mb.....

Thank you.

**Comment by ralight** [comment]
The relevant configuration options are:

* max_inflight_bytes (per client)
* max_inflight_messages (per client)
* max_packet_size (transmit/receive only, but will affect overall resource usage if messages are rejected)
* max_queued_bytes (per client)
* max_queued_messages (per client)
* max_connections (per listener)

These can be used to limit the resources available.

Setting `memory_limit` has a direct effect on the possible size of mosquitto.db with the current implementation, because all messages are also stored in memory.

**Comment by itadakimatsu97** [comment]
@ralight
Thank you!
