### ISSUE TITLE
Finding subtopics

### ISSUE THREAD

**Issue by bulbaasd24** [eclipse/mosquitto#1687]
Assuming a broker receives and a new packet. Is it possible to find out which topic/sub-topic this new message belongs to a subscriber?
Example:  sub with subscriptions - a#, b#, c# (3 total)
new pub message - a/z. Hence, we conclude, a/z is a subtopic of a/#

**Comment by ralight** [comment]
I'm afraid I don't quite understand what you mean. We know that a/z is a subtopic of a/# because that is how topic filters work in MQTT.

If you mean is it possible to tell when you publish a message whether there were any subscribers for that topic, then MQTT v5 supports this for QoS 1 or 2 messages by sending the reason code `no-matching-subscribers` in the PUBACK or PUBREC message.

**Comment by bulbaasd24** [comment]
Let's say a subscriber has subscribed to 5 topics. I would iterate through every topic to check if the new publish message is actually a subtopic of any 1 of the 5 topics.
If the new message is a subtopic, I would return true.  
Was expecting if something similar is available in mosquitto.

**Comment by ralight** [comment]
Thanks for the clarification. Your client could use `mosquitto_topic_matches_sub(const char *sub, const char *topic, bool *result)` to check whether a topic matches a particular subscription.

```
void on_message(struct mosquitto *mosq, void *userdata, const struct mosquitto_message *msg)
{
    bool match = false;
    mosquitto_topic_matches_sub("a/#", msg->topic, &match);
    if(match){
        // do something
    }
}
```

The broker should only be sending messages that match your subscriptions of course.

**Comment by bulbaasd24** [comment]
Thanks ralight. Thats exactly what I wanted.

**Comment by bulbaasd24** [comment]
Thanks ralight. Thats exactly what I wanted.
