### ISSUE TITLE
Fresh install fails 1.6.10 on Windows 10 64bit

### ISSUE THREAD

**Issue by DevLocus** [eclipse/mosquitto#1723]
When installing, for the first time on a clean install of Windows 10 64-bit system, the installer throws an error about libssl and libcrypto missing.  There are no links to any dependencies on the download page and no instructions specifying what packages need to be installed first and which version is expected.

**Comment by Tifaifai** [comment]
the solution : install Ubuntu ;)

**Comment by DevLocus** [comment]
Too bad TwinCAT 3 doesn't work on Linux

**Comment by Sumatt92** [comment]
Yeah the same thing happens for me when I try it. Previous version works. The readme actually says that you will need to install dependencies on your own but it seems like that is no longer accurate since I can see the libs in the programs directory. 

Poking around it looks like the x86 and x64 versions of the executable got mislabeled. Really have no idea about this windows installer stuff though... @ralight will have to patch I think.

If your needing this to work immediately you can install the dependancies according to the readme or even download both x86 and x64 binaries and swap the ssl libs.

**Comment by guitarpicva** [comment]
Installing the libssl and libcrypto does not help.

**Comment by guitarpicva** [comment]
Confirming that 1.6.9 appears to be functional.

**Comment by guitarpicva** [comment]
1.6.9 mosquitto_pub.exe does not seem to be functional however.  From linux the topic is accepted, but the exact same syntax from the Win10 installation is met with a format error when it parses the -m message text.
I am going to revert one more level to see if things smooth out.

**Comment by Sumatt92** [comment]
Is -m argument  properly escaped or quoted for windows machine? Ie / vs \

**Comment by Sumatt92** [comment]
With ssl problem, are the dlls the exact same name as what the error message is complaining about?

**Comment by guitarpicva** [comment]
Apparently Windows requires double quotes around switch parameter content.  Thank you for the nudge :)

**Comment by guitarpicva** [comment]
Confirmed 1.6.9 fully functional.  1.6.10 non-functional.  Error on install when the installer attempts to start the program after the installation is complete.  Subsequent attempts will not start on Win10 after installation was completed.  OpenSSL libs are in place per dependencies.

**Comment by ralight** [comment]
Apologies for this, for some reason the openssl libraries for 32-bit and 64-bit got mixed up in the respective installers. It was fixed earlier today.

**Comment by guitarpicva** [comment]
I has a sneaking suspicion. ... not that I would ever do such a thing. ;)  Thanks for the remedy.
