### ISSUE TITLE
MQTT v5 Topic Alias not sent to client?

### ISSUE THREAD

**Issue by vera** [eclipse/mosquitto#1757]
When using MQTT v5 topic aliases, I expected the Topic Alias property to be sent onwards to the client (subscriber) by the broker when a Topic Alias Maximum was set by the subscriber.
Instead, the broker seems to remove the Topic Alias property and re-insert the full topic name.

Here's what I did:

**Publisher:**
```
$ mosquitto_pub -t "test" -V 5 -D publish topic-alias 1 -D connect topic-alias-maximum 23 -d -l
Client (null) sending CONNECT
Client auto-1855C4B1-5EED-4087-0638-13B76F26384C received CONNACK (0)
hallo
Client auto-1855C4B1-5EED-4087-0638-13B76F26384C sending PUBLISH (d0, q0, r0, m1, 'test', ... (5 bytes))
hallo
Client auto-1855C4B1-5EED-4087-0638-13B76F26384C sending PUBLISH (d0, q0, r0, m2, '(null)', ... (5 bytes))
```

**Subscriber:**
```
$ mosquitto_sub -v -t "test" -V 5 -D connect topic-alias-maximum 42 -F %j -d
Client (null) sending CONNECT
Client auto-80079A30-90E2-1C13-7A76-02257415E7E9 received CONNACK (0)
Client auto-80079A30-90E2-1C13-7A76-02257415E7E9 sending SUBSCRIBE (Mid: 1, Topic: test, QoS: 0, Options: 0x00)
Client auto-80079A30-90E2-1C13-7A76-02257415E7E9 received SUBACK
Subscribed (mid: 1): 0
Client auto-80079A30-90E2-1C13-7A76-02257415E7E9 received PUBLISH (d0, q0, r0, m0, 'test', ... (5 bytes))
{"tst":1595862465,"topic":"test","qos":0,"retain":0,"payloadlen":5,"payload":"hallo"}
Client auto-80079A30-90E2-1C13-7A76-02257415E7E9 received PUBLISH (d0, q0, r0, m0, 'test', ... (5 bytes))
{"tst":1595862466,"topic":"test","qos":0,"retain":0,"payloadlen":5,"payload":"hallo"}
```

Packet capture shows four MQTT Publish Messages. The last two look like this:

```
Frame 87: 81 bytes on wire (648 bits), 81 bytes captured (648 bits)
Linux cooked capture v1
Internet Protocol Version 4, Src: 127.0.0.1, Dst: 127.0.0.1
Transmission Control Protocol, Src Port: 36246, Dst Port: 1883, Seq: 39, Ack: 53, Len: 13
MQ Telemetry Transport Protocol, Publish Message
    Header Flags: 0x30, Message Type: Publish Message, QoS Level: At most once delivery (Fire and Forget)
    Msg Len: 11
    Topic Length: 0
    Properties
        Total Length: 3
        ID: Topic Alias (0x23)
        Topic Alias: 1
    [Topic: test]
    Message: hallo

Frame 90: 82 bytes on wire (656 bits), 82 bytes captured (656 bits)
Linux cooked capture v1
Internet Protocol Version 4, Src: 127.0.0.1, Dst: 127.0.0.1
Transmission Control Protocol, Src Port: 1883, Dst Port: 36244, Seq: 73, Ack: 34, Len: 14
MQ Telemetry Transport Protocol, Publish Message
    Header Flags: 0x30, Message Type: Publish Message, QoS Level: At most once delivery (Fire and Forget)
    Msg Len: 12
    Topic Length: 4
    Topic: test
    Properties
        Total Length: 0
    Message: hallo
```

Why does the second packet (the one sent to the subscriber) include the full topic instead of the topic alias, as it was sent by the publisher? Is there a way to get mosquitto to behave the way I want it to?

Edited to add: I am using v1.6.10.

**Comment by ralight** [comment]
MQTT in general keeps the publisher and subscriber very much decoupled from one another, so there is no expectation that topic aliases on the subscriber have any relationship to those on the publisher. Having said that, it is not unreasonable that that might be the case. Perhaps adding an option so that incoming topic aliases are mirrored to subscribers would be a good idea.

**Comment by veracl** [comment]
I see. The MQTT v5 specification seems to be a bit unclear on who sets the mappings. I am not sure how the specification authors intended this to be implemented.

> The sender decides whether to use a Topic Alias and chooses the value. It sets a Topic Alias mapping by including a non-zero length Topic Name and a Topic Alias in the PUBLISH packet. The **receiver** processes the PUBLISH as normal but also sets the specified Topic Alias mapping to this Topic Name.

(Emphasis mine) Either broker or subscriber could be the receiver. I have found that different broker and client implementations interpret this differently.

However, the specification also states under "3.1.2.11.5 Topic Alias Maximum":

> This value indicates the highest value that the Client will accept as a Topic Alias sent by the Server. The Client uses this value to limit the number of Topic Aliases that it is willing to hold on this Connection. The Server MUST NOT send a Topic Alias in a PUBLISH packet to the Client greater than Topic Alias Maximum [MQTT-3.1.2-26]. A value of 0 indicates that the Client does not accept any Topic Aliases on this connection. If Topic Alias Maximum is absent or zero, the Server MUST NOT send any Topic Aliases to the Client [MQTT-3.1.2-27].

This implies that the broker can send Topic Aliases on to the subscriber if they are below the Topic Alias Maximum. If it doesn't, then what is the purpose of the Topic Alias Maximum?

In my use case, which is perhaps a bit unusual, the constrained IoT device isn't only a publisher but also a subscriber and gets sent many messages, which is why I am looking to use aliases to reduce the topic bytes for these incoming PUBLISH messages.

It would be great if support for this could be added to mosquitto. Since I found that some client implementations depend on the broker setting the mappings, it would need to be an optional feature. I think a simple pass-through of Topic Aliases should be quite easy to implement?

If publisher and subscriber must remain uncoupled, perhaps this alternative would work: The subscriber sets its own Topic Alias by sending a PUBLISH message including a Topic Alias property on the topic it is subscribed to. This Topic Alias may be different from the one used by the publisher. After that, the broker sets a zero-length topic and the subscriber's Topic Alias in outgoing PUBLISH messages on that topic.

**Comment by ralight** [comment]
In terms of how this is implemented, my understanding is as follows:

"Normal" publish - topic string is set, a topic alias property is not set.
First alias publish - topic string is set to `hello`, and a topic alias property is set to `1`. This is the sender telling the receiver to register a new topic alias `1` that equates to the topic `hello`, which is only valid for messages that are sent from this specific sender to this specific receiver.
Subsequent alias publish - topic string is not set, topic alias is set to `1`. The receiver now interprets the `1` as being equivalent to the topic `hello`.

This all only applies to a single direction, it is only ever the sender that sets a topic alias. Both the broker and a client can be a receiver, because both brokers and clients can receive PUBLISH messages.

The broker does not "send topic aliases on to the subscriber" in the manner that I think you mean - which I think is publisher sends a topic alias to the broker, the broker then sends that *identical* topic alias to a subscriber. In reality, the broker is free to make a new topic alias when it is publishing messages to any clients, but they are not directly related to any topic aliases that have been sent from a publisher to the broker. In other words, my `hello` topic above could be mapped to an alias of `2` for one subscriber, and `3` for another subscriber. The topic to alias mappings are unique to each client, session, and direction.

The point is that the broker must be the one setting the topic alias to the subscriber, and so it has to initiate that. Mosquitto doesn't do that yet, but it should. There are a few ways it could be done. I'm away right now, but I'll have a think about it.
There are a few ways

**Comment by veracl** [comment]
Yes, that makes sense. Thank you for clearing up my confusion. I never considered that it may be the broker who chooses a new topic alias, not the client.

**Comment by ralight** [comment]
The upcoming 2.1 release does create outgoing topic aliases now, so I'm closing this issue.
