### ISSUE TITLE
Feature: Require configuration to allow access by default

### ISSUE THREAD

**Issue by ralight** [eclipse/mosquitto#1780]
The current Mosquitto default behaviour is to start a listener on port 1883 that is unencrypted and requires no authentication. This makes life very easy for new users wanting to start some MQTT experiments, but means that authentication and encryption are secondary considerations.

This proposal is to change the default behaviour to be more restrictive, so that the broker admin has to take action to allow access.

One way to implement this in a very simple way, would be to have the broker bind the listener to the loopback interface only when running with no configuration file as in `mosquitto -p 1883`. This retains a method of making it easy to do local testing whilst providing some protections.

I don't think this simple method goes far enough, however. If the action of specifying a configuration file means the loopback behaviour is disabled, then most packages from e.g. Linux distributions will have no benefits compared to the current situation. This means changing to a default behaviour of `allow_anonymous false`. Even this change seems inadequate, because it is easier for a broker admin wanting quick results to add `allow_anonymous true` than to configure users, but it is at least a barrier to make them consider authentication.

Please comment if you have any thoughts on the above.

**Comment by gdt** [comment]
I support changing defaults to listen to loopback (which must include ::, not just 127.0.0.1) by default, and to disallow anonymous users by default.

I don't think it's reasonable to consider these defaults inadequate because an admin might do something unsafe rather than setting up users properly.  The responsibility of mosquitto is to 1) have safe defaults and 2) provide mechanisms for reasonable security.

**Comment by ralight** [comment]
These changes have now been made in the `develop` branch.
