### ISSUE TITLE
[feature request] bridge exclude mode

### ISSUE THREAD

**Issue by GopherJ** [eclipse/mosquitto#1864]
I search a lot how to do bridging using excludeded topics. Let's say if I would like to bridge topic except `should_excluded_topic`.

Is there a way to do this?

**Comment by GopherJ** [comment]
An example will be:

```
topic !should_excluded_topic # both 0 b_local/  b_remote/
```

**Comment by ralight** [comment]
This is tricky, because what the bridge is doing when you define a topic is make a subscription. It's not possible in mqtt to subscribe to b_local/# but with topic exclusions within that subscription.

**Comment by GopherJ** [comment]
@ralight Thanks for your reply, can we keep this open then? Or it'll should be mqtt protocol side?

I have two brokers, they are for different purpose and the topics used by them don't have intersection but one broker uses lots of topics the other use only one topic.

So I would like to use `!` to make the bridge conf

**Comment by ralight** [comment]
I'd prefer to close this, there's not really anything I can usefully do to fix it for you. I don't think you'll get anywhere approaching this from the protocol side, but you're welcome to try of course.

Without knowing the specifics of what you are doing, it sounds as though that because the topics don't intersect you could just configure multiple topics for your bridge.

**Comment by GopherJ** [comment]
@ralight Ok thanks, I'll write a script to generate bridge conf for this kind of purpose
