### ISSUE TITLE
shared library error while running mosquitto_sub

### ISSUE THREAD

**Issue by darkasassin44** [eclipse/mosquitto#1892]
Cloned the GitHub repository and built successfully.
In first terminal :
```
conceptbug95@ubuntu:~/mosquitto/src$ ./mosquitto
1605249716: mosquitto version 1.6.12 starting
1605249716: Using default config.
1605249716: Opening ipv4 listen socket on port 1883.
1605249716: Opening ipv6 listen socket on port 1883.
1605249716: mosquitto version 1.6.12 running
```
And in second terminal :
```
conceptbug95@ubuntu:~$ cd mosquitto/client/
conceptbug95@ubuntu:~/mosquitto/client$ ls
client_props.c   CMakeLists.txt  pub_client.c  pub_test_properties  sub_client_output.c
client_props.o   Makefile        pub_client.o  rr_client.c          sub_client_output.o
client_shared.c  mosquitto_pub   pub_shared.c  rr_client.o          sub_test_properties
client_shared.h  mosquitto_rr    pub_shared.h  sub_client.c
client_shared.o  mosquitto_sub   pub_shared.o  sub_client.o
conceptbug95@ubuntu:~/mosquitto/client$ ./mosquitto_sub -h 10.0.0.254 -t tags
./mosquitto_sub: error while loading shared libraries: libmosquitto.so.1: cannot open shared object file: No such file or directory
```

Please tell me if someone knows the solution.

**Comment by ralight** [comment]
What is happening here is that the runtime linker doesn't know where to find the shared library because it's not in one of the directories that it is configured to look in. There are two solutions.

Permanent:
* Run `sudo make install` - this installs the library to `/usr/local/lib/`.
* Run `sudo ldconfig` - this updates the cache for the runtime linker, so it knows the library exists

Temporary:
* Set the `LD_LIBRARY_PATH`  environment variable to point to the path where the library is. The runtime linker looks at the directories in this variable as well as the normal ones.

Some examples:
```
# Environment variable only applies to this command. Path is relative.
LD_LIBRARY_PATH=../lib ./mosquitto_sub ...
```
```
# Environment variable only applies to this command. Path is absolute.
LD_LIBRARY_PATH=~/mosquitto/lib ./mosquitto_sub ...
```
```
# Environment variable is persistent throughout this shell session (so won't need setting again). Path can be relative/absolute.
export LD_LIBRARY_PATH=../lib
./mosquitto_sub ...
./mosquitto_sub ...
```

**Comment by darkasassin44** [comment]
@ralight Thank you for your kind and quick reply! All executables are working correctly. I'll close this issue, but I have one more question.
When I installed with ubuntu ppa installation, I could check the status and manage the broker with `sudo service mosquitto BLAHBLAH`, with source installation how can I monitor and manage(start, kill, restart...) the broker?
