### ISSUE TITLE
Mosquitto clients 2.0.2 fails to communicate with Mosquitto broker 1.6.12

### ISSUE THREAD

**Issue by Peoh** [eclipse/mosquitto#1957]
Hello,

We work with mosquitto since 2 years, and it works like a charm. We update to last versions as soon as possible to fix the possible issues, but this time I think I encountered one :)

Setup to reproduce the error:
- Broker on ARM board, version 1.6.12, with a simple configuration (see below)
- Clients (mosquitto_sub was used) version 2.0.2, on Ubuntu 16.04, on x64 machine.

This is what I tested
- On the ARM board, applications using libmosquitto (1.6.12) works fine
- On the ARM board, mosquitto_sub works fine
- On the x64 machine, mosquitto_sub c'ant connect

This is the what I got from the broker (1.6.12)
~~~
mosquitto -c /etc/mosquitto/mosquitto.conf -v
1608125082: mosquitto version 1.6.12 starting
1608125082: Config loaded from /etc/mosquitto/mosquitto.conf.
1608125082: Opening ipv4 listen socket on port 8883.
1608125082: Opening ipv6 listen socket on port 8883.
1608125082: Warning: Address family not supported by protocol
1608125082: mosquitto version 1.6.12 running
1608125389: New connection from 192.168.1.44 on port 8883.
1608125389: Client <unknown> disconnected due to protocol error.
1608125449: New connection from 192.168.1.44 on port 8883.
1608125449: Client <unknown> disconnected due to protocol error.
~~~

And this is what I got from mosquitto_sub on the x64 (2.0.2)
~~~
mosquitto_sub -h 192.168.1.90 -p 8883 -t "#" -d -v                         
Client (null) sending CONNECT
Client (null) sending CONNECT
~~~
mosquitto_sub is unresponsive and I have to kill it with a SIGKILL (or wait some time).

The configuration on the broker is the following (really minimal):
~~~
user mosquitto
set_tcp_nodelay true
port 8883
~~~

I would like to note that the mosquitto_sub worked with a previous version on my x64 machine. After update to  2.0.2 it does not work.

If you want more tests or details, feel free to ask.

**Comment by ralight** [comment]
Thanks for the report. There are two things to address:

First mosquitto_sub not responding to ctrl-c. This occurred because it was assuming a successful connection would be made, and then try to disconnect gracefully. If the connection wasn't made, as in this case, it couldn't disconnect gracefully but wouldn't quit any other way.

Second, the client not connecting. This is because the behaviour of the mosquitto clients has changed if you use port 8883. Port 8883 is reserved for TLS encrypted MQTT connections, and the clients will now load the system CA certificates and use TLS mode if you use port 8883 and don't specify your own certificates. So I'd suggest either changing to use port 1883, or adding TLS encryption to your listener.

**Comment by Peoh** [comment]
Thank you for the update, I was using 8883 port because I will use TLS encryption later in the project. I will come back to 1883 for the development phase.
Thanks a lot!
