### ISSUE TITLE
cmake 安装2.0.0 版本 提示未定义动态库，该如何解决

### ISSUE THREAD

**Issue by phplpf** [eclipse/mosquitto#1970]
mosquitto_sub -v -t mytest/#  
mosquitto_sub: symbol lookup error: mosquitto_sub: undefined symbol: mosquitto_property_check_all

**Comment by ralight** [comment]
The `mosquitto_property_check_all()` function has been available since version 1.6, so my guess would be that you have another older version of libmosquitto.so.1 installed.

If you run `ldd` on your copy of mosquitto_sub (i.e. `ldd /usr/local/bin/mosquitto_sub`, or whatever the correct path is) then it will tell you what library path it is using, and you can check whether that matches what you installed,

**Comment by ralight** [comment]
I don't think this is directly a Mosquitto problem, so I'm closing this issue. Please feel free to reopen if you have more details of what is wrong.
