### ISSUE TITLE
Mosquitto behind a reverse proxy: Error: A network protocol error occurred when communicating with the broker.

### ISSUE THREAD

**Issue by lucassardois** [eclipse/mosquitto#2009]
I'm trying to run mosquitto behind a reverse proxy. When I try to publish a message to a topic from my laptop I get the following error: 
```
$ mosquitto_pub -d -h mosquitto.mydomain.com -p 80 -t "test" -m "working"
Client mosq-LNyid6GQYX9pOJGlQs sending CONNECT
Error: A network protocol error occurred when communicating with the broker.
```

Both the broker and the publisher use mosquitto 1.6.12.

The broker run inside minikube on Openstack and use the ingress Nginx proxy reverse proxy.

**Comment by ralight** [comment]
I think this is a nginx question rather than mosquitto. mosquitto_pub only talks MQTT over TCP. If you want to connect it via nginx, then it will need to be configured to with with TCP streams rather than HTTP connections. The details here might be relevant: https://docs.nginx.com/nginx/admin-guide/load-balancer/tcp-udp-load-balancer/

**Comment by lucassardois** [comment]
Thanks for the information I fixed it!
