### ISSUE TITLE
latest tag on dockerhub doesn't point to 2.0.5

### ISSUE THREAD

**Issue by sunbit** [eclipse/mosquitto#2028]
I assume that this is a mistake, unless there is any reason why it still points to 1.6.12 ?

Thank you

**Comment by ralight** [comment]
It is deliberate.

This is because the change to 2.0 is breaking, so anybody who has been using `latest` will need to make changes to their configuration otherwise their broker may fail to work as they expect. Leaving it on `1.6.12` for a while gives people the chance to migrate. I will be making the change only after announcing it in advance.

**Comment by sunbit** [comment]
Makes sense! I never use `latest` only specific tags (where available) to avoid unexpected situations just like you explain. What i do is monitor `latest` tags to be aware of new available version, that's why i end up detecting this.

Thank you for the explanation.
