### ISSUE TITLE
Mosquitto Subscribe client is unable to print binary messages sent

### ISSUE THREAD

**Issue by saumilsdk** [eclipse/mosquitto#2034]
Mosquitto Subscribe client is unable to print binary messages sent

**Comment by ralight** [comment]
This video shows me running mosquitto, then using mosquitto_sub in three ways to output a binary image file.

1. `mosquitto_sub -t binary -C 1` this receives a single message and prints it to screen in binary.
2. `mosquitto_sub -t binary -C 1 > recv.png` this receives a single message, and writes it to a file - this verifies that the data is correctly being printed out.
3. `mosquitto_sub -t binary -C 1 -F %x` this receives a single message and prints it out in hex format.

https://user-images.githubusercontent.com/79578/105157489-eda5e080-5b04-11eb-9f36-367b7378bdbc.mp4

Which method are you using, and in what way doesn't it work? The first method will give odd results because the terminal doesn't like binary.

**Comment by ralight** [comment]
I've given a solution to printing binary messages, so I'm closing this. If it's still a problem for you, please reopen and add more details.
