### ISSUE TITLE
Question about RC 141, RC 19

### ISSUE THREAD

**Issue by itadakimatsu97** [eclipse/mosquitto#2062]
Dear Developer,

Could you kindly explain something about?
1. RC 141, how many case that lead to this error.
2. RC 19, it is not defined yet. I already searched it but no reference. I hope you have some opinion about this error.

Thanks so much.

**Comment by ralight** [comment]
It's a bit difficult to say without knowing where you get this code, but 141 could occur in an on_disconnect_v5 callback to indicate the server disconnected the client due to a keepalive timeout. 19 is most likely a Mosquitto error code which is MOSQ_ERR_KEEPALIVE, again related to clients not communicating within their keepalive timeout.

**Comment by itadakimatsu97** [comment]
@ralight 
Thank you!
I got 141 firstly, then lead to 19.
It seems like keepalive timeout issue.
