### ISSUE TITLE
Hello, when I was using the MQTT client, a deadlock problem occurred during testing.

### ISSUE THREAD

**Issue by X-Crack** [eclipse/mosquitto#2155]
During use, I set the port number to: 61613
But in the deadlock, I paused the program and found that the port number was 2.

**### After investigation, the mosquitto__set_state(mosq, mosq_cs_connected); function will cause the program to deadlock.**

My operating system: ubuntu20.04

I enabled multi-thread support.

And other options are closed.

WITH_SRV=no
WITH_WEBSOCKETS=no
WITH_TLS=no
WITH_DOCS=no
WITH_BUNDLED_DEPS=no
WITH_CJSON=no
**WITH_THREADS=yes**

![mqtt](https://user-images.githubusercontent.com/45416520/112707949-f7bfd300-8ee9-11eb-8f73-fcebc462f6e0.png)

**Here is the deadlock position**

![2](https://user-images.githubusercontent.com/45416520/112708140-3d30d000-8eeb-11eb-8f37-46670c32e74f.png)

**Comment by X-Crack** [comment]
The same problem will also appear in
machine: armv7l platform

**Comment by ralight** [comment]
Could you please provide a minimal example that shows this behaviour?

**Comment by X-Crack** [comment]
[example.zip](https://github.com/eclipse/mosquitto/files/6222343/example.zip)

ubuntu20.04 deadlock version: v2.0.6-v2.0.9
ubuntu20.04 no problem version: https://github.com/eclipse/mosquitto/tree/develop


ARM system deadlock version: https://github.com/eclipse/mosquitto/tree/develop

ARM no problem version: v2.0.6-v2.0.9

@ralight

**Comment by ralight** [comment]
When I said a minimal example I was hoping you would spend the time to pinpoint the part that is causing the problem and send me that, rather than just putting your whole project in a zip file and expecting me to search through and find the problem for you.

I've spent a few minutes looking at it. First off, don't include `mosquitto_internal.h`, it's not for you - it's an internal header for use inside the Mosquitto project only. Secondly, you're using both `mosquitto_loop_start()/mosquitto_loop+stop()` and `mosquitto_loop()`. You should decide which one of those to use and just use one.

I'm sure that the header misuse is producing the problem with the socket, and the mix of functions is causing the deadlock.

I'm afraid if that isn't the problem then you will have to provide an actual minimal example that demonstrates the problem and nothing else. If you think it's unreasonable of me to ask that, please do consider what you're asking of me.

**Comment by X-Crack** [comment]
OK, I understand, please give me time.

**Comment by X-Crack** [comment]
mosquitto_internal.h
This header file must be included before it can be used struct mosquitto* 

Otherwise, the compilation will report an error

**Comment by ralight** [comment]
If you include `mosquitto.h` you can use a pointer to a `struct mosquitto`. You are not allowed to look inside the `struct mosquitto` structure. The only way you can create a `struct mosquitto *` instance is with `mosquitto_new()`.

**Comment by X-Crack** [comment]
`#include <iostream>
#include <stdio.h>
#include <unistd.h>
#include <assert.h>
#include <mosquitto.h>
#include <mqtt_protocol.h>
class callback_object{

};
int main()
{
    callback_object obj;
    char user[128] = "admin";
    char pass[128] = "password1006";
    mosquitto* mosq_data = mosquitto_new("1", true, &obj);
    assert(0 == mosquitto_lib_init());
    assert(0 == mosquitto_int_option(mosq_data, MOSQ_OPT_PROTOCOL_VERSION, MQTT_PROTOCOL_V311));
    assert(0 == mosquitto_username_pw_set(mosq_data, user, pass));
    assert(0 == mosquitto_connect(mosq_data, "47.96.180.xx", 61613, 60));   // dolock wait ?????

    assert(0 == mosquitto_publish(mosq_data, nullptr, "test/Group/GACFCADevice/DataDetail/0000001_00000001", 4, "hello", 0, false));

    assert(0 == mosquitto_loop_start(mosq_data));


    sleep(99999);
    mosquitto_destroy(mosq_data);
    mosquitto_lib_cleanup();
    return 0;
}
`
In this way, the server cannot be connected, you must set struct mosquitto and include mosquitto_internal.h

**Comment by X-Crack** [comment]
![20210330000922](https://user-images.githubusercontent.com/45416520/112866386-518feb00-90ec-11eb-8b20-7fc3f984e78c.png)
![20210330001002](https://user-images.githubusercontent.com/45416520/112866391-52288180-90ec-11eb-81a5-6806f6736da5.png)

**Comment by ralight** [comment]
```
    if (mosq->protocol == MQTT_PROTOCOL_V5)
```

Yes, you aren't allowed to do that. It's an opaque structure, you can't look inside it.

**Comment by X-Crack** [comment]
Since it is an incomplete pointer and cannot be referenced, why should this parameter be given, so "mosquitto_internal.h" must be included

Otherwise, move the complete structure of struct mosquitto{} to "mosquitto.h" so that C++ can be compiled.

**Comment by X-Crack** [comment]
> ```
>     if (mosq->protocol == MQTT_PROTOCOL_V5)
> ```
> 
> Yes, you aren't allowed to do that. It's an opaque structure, you can't look inside it.


In the example you gave, this kind of judgment was used, but I think it should be made public. After all, we will not deliberately modify the contents.

If you don't use "struct mosquitto" to set the IP address and port, you will not be able to connect to the MQTT server.

**Comment by ralight** [comment]
I'm sorry, but you are mistaken. The problem is with your code because you are trying to access data which you do not have the rights to. In C++ terms, this struct is completely private. You MUST not attempt to access it. This is crucial. Opaque structs are a deliberate design decision so that the contents of the struct can be changed from one release to the next without the end developer ever knowing. If I make the struct public, it has to stay entirely unchanged *forever*, or else every single program that makes use of it will break.

To connect to an MQTT server you use `mosquitto_connect(mosq, host, port, keepalive);`. There is no need for you to modify the struct contents.

I'll repeat myself for effect - if you are trying to access the internals of `struct mosquitto` you are trying to use the library incorrectly and your program will certainly crash in a future release. Do not do it.

**Comment by X-Crack** [comment]
Yes, I have used "mosquitto_connect" to connect to the MQTT server, but the result is not. The current situation is unable to connect, just like the above code, a mini example, I hope you can point out the error. Post the correct usage method, and hope that you or your colleagues can update the smallest example, so that we Asians will no longer be confused about the development, thank you very much.

But I hope to support libuv libevent in the future to make it a more powerful and robust open source project.

@ralight

**Comment by ralight** [comment]
There are minimal, well commented examples here:

https://github.com/eclipse/mosquitto/blob/master/examples/publish/basic-1.c
https://github.com/eclipse/mosquitto/blob/master/examples/subscribe/basic-1.c

**Comment by X-Crack** [comment]
But I still think that it is good to make the structure of struct mosquitto public, because we can do more judgments during the development process, otherwise there is really no objection to giving this parameter, it is better to carry out a layer of packaging Make it completely private, what do you think? .

Even a private method can be hard accessed by offset, but I don't think this is necessary.

**Comment by ralight** [comment]
If the struct becomes public then I could never change it without breaking every single program that used it. As it is, I can change the contents of the struct in any way whatsoever and it does not matter to any program that developed against this library since 2012. In practice that means that had the struct been public, I would have had to break existing programs multiple times over the past 9.5 years. Breaking API and ABI compatibility is really really annoying for developers. I don't want to do that - using an opaque struct lets me maintain compatibility.

It is never going to be public.

There is essentially nothing you could do with a public struct that you couldn't do with an opaque struct and a public interface.
