### ISSUE TITLE
How to leave existing password hashes in password file when adding a new one

### ISSUE THREAD

**Issue by jayjupdhig** [eclipse/mosquitto#2211]
First:

```
root:HASH_x
```

Then:

```
root:HASH_x
root2:MY_PASSWORD_IN_PLAIN_TEXT
```

After executing `mosquitto_passwd -U ./passwd`:

```
root:HASH_y
root2:HASH_z
```

-> Which means: The command  `mosquitto_passwd -U ./passwd` does also chaned already-hashed entries which is very very strange. How to prevent that?!

**Comment by ralight** [comment]
The `-U` option is only for converting a password file with plain text passwords in to hashed passwords. It doesn't support mixed hashed and plain text passwords. It isn't a way for you to manually add plain text passwords to your file and hash them later.

**Comment by jayjupdhig** [comment]
When i see it right, the hash always begins with `$6$ ... ` and has alway the same lenght; so don't don't see any problems to recognize what is plain text and what is already hashed.

I always wonder about different software developers - they are able to implement high-level code, but they are not able to implement such trivial things like that... ;-)

And i ask me why...

Maybe that can be added to to ToDo-list for the next version...?

**Comment by ralight** [comment]
`mosquitto -U` was introduced to allow users to move from plain text password files to hashed password files. Plain text passwords were the only choice in version 0.15 and earlier so this was a necessary change when moving to version 1.0. This happened over 8 years ago, there has been no reason to use plain text password files since then. I am not interesting in adding more features to this ancient feature, I think it would be a waste of my time.

**Comment by jmar83** [comment]
Oh - i didn't mean to use plain unhashed passwords, i just meant a feature a add a new (plain) password entry then using the mosquitto_password tool that ONLY make hash from the unhashed entries - not make hashes from other (already) hashed entries...

(Now i'm at home and that's my personal account.)

So:

First:

```
root:HASH_x
```

Then:

```
root:HASH_x
root2:MY_PASSWORD_IN_PLAIN_TEXT
```

After executing mosquitto_passwd -U ./passwd:

```
root:HASH_x (STILL HASH_x, leave it unchanged!!)
root2:HASH_y
```

(instead of that what i meant in my initial post)

**Comment by ralight** [comment]
I don't understand why this is an advantage. You've made a single call of mosquitto_passwd into an editor plus a call to mosquitto_passwd. Why not just add the hashed password in one go?

**Comment by jmar83** [comment]
**_"Then"_** means maybe a few months later; not a few seconds...

With the current implementation, i have a add new (unhashed) entries to a temporary file, the copy it from the temporary to the credentials file configured in mosquitto.conf (/etc/mosquitto/passwd in my case)

**Comment by ptjm** [comment]
Why not just use mosquitto_passwd to add the hashed password directly to the file? You were gratuitously insulting to Roger in one of your notes above, but this is not so much a matter of the developer not being able to implement this, it's just that what you're asking for makes no sense, so of course nobody would implement it.

**Comment by jayjupdhig** [comment]
OK, anyway... problem solved by closing issue.
