### ISSUE TITLE
Denied Publish When push message to Shared Subscription topic

### ISSUE THREAD

**Issue by anhtuanluu36** [eclipse/mosquitto#2261]
MQTT Version 2.0.11
When I push a message to the shared subscription topic "'$share/som/topic'". I have an error 
`Denied PUBLISH from MQTT_FX_Client (d0, q0, r0, m0, '$share/som/topic'`

Here is the content of the mosquitto.conf:

```
listener 1883
log_type all
persistent_client_expiration 7d
allow_anonymous true
persistence true
persistence_location /mosquitto/data/
acl_file /mosquitto/config/acl_file
```

Here is the content of the acl_file:
`topic readwrite $share/som/+`

**Comment by Daedaluz** [comment]
Not sure if you can publish messages on those topics.
They can be used in a fashion so that messages can be received in an alternating way between different clients within a shared topic group.

I found a very good explanation of it here:
https://www.hivemq.com/blog/mqtt5-essentials-part7-shared-subscriptions/

In your case the "group" would be "som" and would listen to any one level topic messages (topic '+')

Publishing on topic "topic" would be received on a shared subscription with filter "$shared/som/+"

**Comment by linxingyang** [comment]
I make the same mistake.

sub, the topic is ` \$share/foo/bar`
```shell
mosquitto_sub  -t \$share/foo/bar -V mqttv5
```
pub, the correct topic is `bar`
```shell
mosquitto_pub  -t bar -V mqttv5  -m "test message" 
```

when you publish to `\$share/foo/bar`,  it cause the problem `Denied Publish When push message ...`
```shell
mosquitto_pub  -t \$share/foo/bar -V mqttv5  -m "test message" 
```

linxy.

**Comment by ralight** [comment]
I think this has been resolved now?
