### ISSUE TITLE
unable to connect Mosquitto Bridge (2.014)  to moquette broker

### ISSUE THREAD

**Issue by rjaekle-ms** [eclipse/mosquitto#2394]
**Mosquotto Version** 2.014 (  in all cases)
**Platform Windows** 64 Bit  ( in all cases)

**Description:** 

The following configuration works ( publishe/subscroibve in both directioons :-) )

`MQTT Explorer <--> MQTT Broker Bridge (Mosquittor A)    <--> Mosquittop Borker (B)   <--> MQTT Explorer`

But as soon I replace  the Mosquitto broker (B) with my moquette broker then I does not work.

I drilled down the problem and I think the root cause is in the wireshark capture file ( see below)
The figure below shows the data which are send by the mosquitto broker which is configured as bridge.

![Mosquitto-Bridge](https://user-images.githubusercontent.com/77733798/143886926-24e39ffa-c545-470f-9608-432c15f7c6fd.png)

For me it looks like that mosquitto sends the protocoll version 0x84  (132)  but in 0x40 (4) is expected.
So moquette does not accept the MQTT connection because of wrong a MQTT version header. This is what I see in  source code of the moquette Broker implementation too.

Unfortunatelly the MQTT Spec does not say anything about the MSB (2^7)  oin the MQTT protocoll header

Is this a bug or do I someting wrong here?

Thanks in advance
Reinhold

**Comment by cjmaynard** [comment]
What happens if you set `try_private false`?

**Comment by rjaekle-ms** [comment]
Hello @cjmaynard 
I will check it ASAP and let you know  the outcome.
Thanks for the hint.

**Comment by rjaekle-ms** [comment]
Hello @cjmaynard 

now it works fine. Many thanks for the hint.
I did not recognise that the default value of `try_private`  is set to  `true`

Cheers
Reinhold

**Comment by rjaekle-ms** [comment]
I will close this issue.
set  `try_private false`  solves my problem

**Comment by cjmaynard** [comment]
The problem with `try_private true` is the undocumented use of the most significant bit of the [Protocol Level](http://docs.oasis-open.org/mqtt/mqtt/v3.1.1/errata01/os/mqtt-v3.1.1-errata01-os-complete.html#_Toc442180843)/[Protocol Version](https://docs.oasis-open.org/mqtt/mqtt/v5.0/os/mqtt-v5.0-os.html#_Toc3901037) byte.

Wireshark knows nothing about that bit because it's strictly interpreting the entire byte field according to the documentation.  Ideally, the use of this bit could be added to the official specification(s), but even if that doesn't happen or won't happen, then it would still be useful if Wireshark were able to interpret the bit according to how it's actually being used in practice.  That would help anyone immediately understand why the bit is set and thus how to unset it, if needed.

With this in mind, I would suggest raising a [Wireshark Issue](https://gitlab.com/wireshark/wireshark/-/issues) for this, and if possible, to provide a patch that implements the desired functionality.  Note that this suggestion is not directed at @rjaekle-ms specifically, but to the mosquitto community in general.

**Comment by hylkevds** [comment]
It may make more sense for mosquitto to respond to the other side closing the connection on connect by logging that try_private failed, and trying again without try_private. The fact that someone has to use wireshark to debug non-standard behaviour is a problem in itself!

**Comment by cjmaynard** [comment]
> It may make more sense for mosquitto to respond to the other side closing the connection on connect by logging that try_private failed, and trying again without try_private.

Yes, but then every connection attempt would still incur that initial connection failure until the `mosquitto.conf` file was updated to set `try_private false`.  And so without a permanent failure, the problem may go unnoticed and thus may never be changed to correct it.

**Comment by hylkevds** [comment]
That's why you should at least log the failure.
If people care about the overhead they'll go looking in the logs. If they don't care, then they don't care. :)

**Comment by cjmaynard** [comment]
I agree that the failure should be logged, but I don't agree with _automatically_ trying again with `try_private false`.  And people do care about failures and should certainly look at logs when they occur, but you basically hide the problem by automatically trying again with `try_private false`, and so it won't be as obvious that there is a problem to look at.  I would say that people generally don't examine logs when everything appears to be working fine.  I simply think it's better to log the failure but let it fail and leave it up to someone to permanently fix it.

And while it shouldn't be necessary to use Wireshark to help troubleshoot this problem, it certainly doesn't hurt to see the bit dissected according to its use if someone does happen to use Wireshark to look at the connection problem, which they might have to do anyway even if the failure is logged because older implementations won't have logged the failure.
