### ISSUE TITLE
Mosquitto not work in openwrt 21.02.1 after upgrade from 19.07.8

### ISSUE THREAD

**Issue by userosos** [eclipse/mosquitto#2429]
Hi all! I used Mosquitto on the openwrt 19.07.8 r11364-ef56c85848 with the config:
log_dest file /var/log/mosquitto.log
log_facility 5
log_type debug
log_type error
log_type warning
log_type notice
log_type information
password_file /overlay/mosquitto/users.list
acl_file /overlay/mosquitto/mosquitto.acl
In openwrt 19.07.8 and an older firmware it worked ok. Today i upgraded to OpenWrt 21.02.1 and it not works.

**Comment by Daedaluz** [comment]
can you provide some more clues to why it isn't working?
In what way does the problem present itself (when you are connecting from another computer or locally et.c)?
logs or any error messages?

maybe a mosquitto version difference would also help.
somewhere down the 2.x.x  version, default listener only accepts local connections for example.

**Comment by userosos** [comment]
> can you provide some more clues to why it isn't working? In what way does the problem present itself (when you are connecting from another computer or locally et.c)? logs or any error messages?
> 
> maybe a mosquitto version difference would also help. somewhere down the 2.x.x version, default listener only accepts local connections for example.

No, sorry. Now i installed openwrt 19.07.8. Because it critical for me.

**Comment by Daedaluz** [comment]
I looked up mosquitto versions between [19.07](https://git.openwrt.org/?p=feed/packages.git;a=blob;f=net/mosquitto/Makefile;h=1c5bab93a0121ff1f7399a2255809b77259cfcc4;hb=refs/heads/openwrt-19.07) and [21.02](https://git.openwrt.org/?p=feed/packages.git;a=blob;f=net/mosquitto/Makefile;h=78e7b25bd67eb1a687985f315d0d2217bd082b79;hb=refs/heads/openwrt-21.02).

Indeed there is a bump from mosquitto 1.6.15 to 2.0.13.

as the [migration notes](https://mosquitto.org/documentation/migrating-to-2-0/) says, default listening interfaces is only on localhost. you need to configure a listener to listen on more interfaces (or all) with `listener 1883 0.0.0.0` added to your config.

without further logs / explanation what the issue was, I'm just guessing this is what you are having issues with.

**Comment by userosos** [comment]
@Daedaluz I hope that i will test it on next wekeend. How i can make logs because in  /var/log/mosquitto.log was empty (file not exist).

**Comment by userosos** [comment]
> as the [migration notes](https://mosquitto.org/documentation/migrating-to-2-0/) says, default listening interfaces is only on localhost. you need to configure a listener to listen on more interfaces (or all) with `listener 1883 0.0.0.0` added to your config.

Its works! Thx!
