### ISSUE TITLE
dynamic-security.json file is full of duplicate entries for clients and roles

### ISSUE THREAD

**Issue by ado-git** [eclipse/mosquitto#2470]
client and role entries repeat hundreds of times. I have 4 users and 4 roles, and the file is 200kbs long already, and it keeps growing. The interesting part is that moquitto keeps working fine.

It´s good to know that i frequently enable/disable the users via the dinamic security plugin and also change passwords. I´ve done it hundreds of times just for one of this 4 users. But entries are duplicate for each of this 4 users and the roles assigned to them.

It has to be a bug because it happens on ubuntu server, but not in windows, as far as i have tested.

version: focal,now 2.0.14-0mosquitto1~focal1 amd64 on Ubuntu 20.04.4 LTS
========================
root@xxxxxxx:~# apt list -a mosquitto
Listing... Done
mosquitto/focal,now 2.0.14-0mosquitto1~focal1 amd64 [installed]
mosquitto/focal 1.6.9-1 amd64

**Comment by m1027** [comment]
Same here: mosquitto works, but there are many duplicate entires in dynamic-security.json. The duplicates are also listed when the admin lists users, groups etc.

mosquitto-2.0.14 on Gentoo.

**Comment by ralight** [comment]
This appears to be caused by the dynsec plugin being loaded more than once, which isn't currently allowed but wasn't being checked for by the plugin.

For 2.0.15 I am disabling this behaviour, so your config file will need modifying. If you're using `per_listener_settings true` then I'm afraid there isn't currently a satisfactory solution.

For 2.1.0 I'm going to try to think of a better solution.
