### ISSUE TITLE
Docker updates without versioning?

### ISSUE THREAD

**Issue by joostvkempen** [eclipse/mosquitto#2484]
For the second time there are updated images on Docker Hub without versioning? Version 'latest' is still 2.0.14 while the digest has changed? Also no change logs or related issues on Github? Is this human error? Someone published this by accident? These kind of updates have me in two minds, how can I be sure they're legit? How can I check the repository isn't hacked or something like that. 

bottomline: when you make changes, make sure to annotate them for the public.

**Comment by joostvkempen** [comment]
and again today.... why is there a new docker version?

**Comment by fjordBob** [comment]
Valid question... is there a answer somewhere ?

**Comment by ralight** [comment]
The mosquitto images are part of the docker "official images" program, which means they are somewhat different to most other images.

One big impact is that the project never builds images itself, it only maintains the dockerfiles that are used to build the images. A recent change was requested by the maintainers of the official images program where projects were using a now defunct gpg keyserver in their Dockerfile. This will have triggered a new build, despite the fact that there were no code changes. Normally you'd not expect a fairly trivial change to have been pushed to make a new image - perhaps it could have waited until the next real image update. But the other difference with the official images is that they are [actively rebuilt](https://github.com/docker-library/official-images/blob/master/README.md#library-definition-files). This means that when the base image is updated, the mosquitto image is also rebuilt. This is the change that you are seeing. In the context of the defunct gpg server change, it was important to push that update so that it would not affect any new rebuilds - such as happened toward the end of March.

I hope that sets your minds at ease.

**Comment by joostvkempen** [comment]
Thank you very much for your time and explanation.

**Comment by fjordBob** [comment]
Thank you very much for the answer!!!
