### ISSUE TITLE
[DynamicSecurity] getGroup command returns clients without priority

### ISSUE THREAD

**Issue by sszczep** [eclipse/mosquitto#2599]
Consider following message on $CONTROL MQTT topic: 
```json
{
  "commands": [
    {
      "groupname": "groupName",
      "command": "getGroup"
    }
  ]
}
```

The returned clients array does not include their priority like roles do. 

I truly believe it is a mistake and should behave same as roles.

Using latest eclipse-mosquitto docker image running on Apple M1.

**Comment by sszczep** [comment]
After further investigation, the same applies to the listGroups command.

**Comment by ralight** [comment]
I'm afraid I think you are mistaken in this case. Roles within a group have a priority for that group, to allow the roles to be ordered as desired. The clients within a group are all treated equally, there are no client priorities. In a similar way, groups in a client have priorities so that groups can be ordered as desired, but this is a client property, not a group property.

I'm going to close this because I think that should clear up things for you (and I'd like to get back on top of issues), but please do feel free to reopen this and add more information if it isn't clear.

**Comment by sszczep** [comment]
Sorry for reopening. Just wanted to let you know that I fully understand your point. Haven't thought of it earlier and the API seemed inconsistent at first glance. I've also noticed that the documentation is not very clear on output formats and not always specifies which properties are optional. Would you mind if I created a PR with my proposal on more clearly specified docs?
