### ISSUE TITLE
Mqtt broker error on cloud run gcp

### ISSUE THREAD

**Issue by Riya-rj-Jain** [eclipse/mosquitto#2924]
Hi,
i am trying to deploy mqtt broker on gcp cloud run with the dockerfile
![image](https://github.com/eclipse/mosquitto/assets/65961848/bbb68e3c-9b9b-4648-9341-76ad27fa755f)
and conf file as 
![image](https://github.com/eclipse/mosquitto/assets/65961848/9de594df-cdc7-45d4-9933-22672435423e)
but i am getting error server disconnected,connected error on gcp cloud run 
![image](https://github.com/eclipse/mosquitto/assets/65961848/9154eb26-4fa8-49e1-ac61-c56c69144686)
can anyone please help.

**Comment by Daedaluz** [comment]
Can you specify if there is some actual functional issue?

I mean, if it's the log-row itself that you are botherd with, it just looks like some type of automated "healt check" that just tests the tcp connection.

**Comment by Riya-rj-Jain** [comment]
yes,i am not able to connect mqtt broker deployed on cloud run and logs showing this error,according to which mqtt broker is not up.

**Comment by Daedaluz** [comment]
There isn't much to walk on here to further troubleshoot the issue.
The broker must be up in order to take connections, and here there are (although from a link-local address) connections beeing made, presumably from a TCP health check monitor because of the socket error and the previous log rows.

I'd take a closer look on the load-balancer.
