### ISSUE TITLE
get MQTT subscription status

### ISSUE THREAD

**Issue by euzun41** [eclipse/mosquitto#2977]
Hello,

I'm unable to receive messages on the topic I've subscribed to in my client software developed using the libmosquitto C APIs.

I've checked the logs on the broker's side and didn't notice any disconnection message on my connection. There doesn't seem to be an issue with my connection on the client side either because I can publish to message different topic.

My problem is that after a certain period (ex: one week no problem), messages from the subscribed topic stop coming through.

**Comment by PepeMax** [comment]
Hello, 

It's surprising that after a while you don't receive any messages. I've had C programs running for months and I've never had this problem. 

Where do the messages come from? Isn't that where the problem is coming from? Try running a _mosquitto_sub -d_ in parallel with your program to activate debug mode and redirect its output to a file to check that you're receiving all the messages.

Then I need more information to help you: where the messages come from, on which broker and where is your C program in your computer network (local network, cloud, etc.)?

Then the last thing is that you use Wireshark, 1 on your machine which sends the messages to see if you send them well, one on your broker and another on your machine where your C program is.

Bye

**Comment by euzun41** [comment]
Hi @PepeMax, thank you for your response message.

I am checking on a different machine and listening to the same topic now. I am wondering, is there any way to get the subscription status from the broker to the client?

In my case: all devices are same LAN, client to client communication.

Best regards

**Comment by euzun41** [comment]
Okay, I found. I can call the 'mosquitto _subscribe' function to get the status periodically. Sorry.

**Comment by euzun41** [comment]
Okay, I found. I can call the 'mosquitto _subscribe' function to get the status periodically. Sorry.
