### ISSUE TITLE
Load balancing mosquitto broker

### ISSUE THREAD

**Issue by win5923** [eclipse/mosquitto#3007]
I'm currently deploying three Mosquitto brokers using Kubernetes, with two of them handling external load balancing. I have configured connections in `mosquitto.conf` to bridge internally. However, when testing retain messages, I noticed that due to load balancing, subscribers only receive half of the messages. The other half is received only when connected to the second external broker. I'd like to know how to ensure that subscribers receive the original quantity of retain messages sent by the publisher.

**Comment by Daedaluz** [comment]
Generally, i think load-balaning mosquitto brokers this way is a bad habbit.
I'm not sure what you are trying to do is possible to do reliably out of the box with mosquitto.
Short version is that the brokers don't share state.

I haven't tried this myself due to the nature of how client-ids play into queuing.
Since the brokers dont share state of which clients are connected and their subscriptions, after a clean session = false client reconnects it will make a new subscription on the second broker while the first broker builds up a huge queue, waiting for the client to come back for its messages just to end up in a situation where the clients will be required to reconnect every now and then to empty queues and receive duplicate messages it already received ages ago as new ones.

You also have a synchronization issue where you don't know which retained message is the latest one due to potential in-flight messages. Partially sent messages on one broker will not match message ids on the other broker either. 

My recommendation is that you pick a broker more suitable for clustering or just roll with one broker.

You could also look into [mosquitto pro](https://cedalo.com/mqtt-broker-pro-mosquitto/high-availability/) version that should have support for HA.

**Comment by win5923** [comment]
Hi @Daedaluz, thanks for your reply.

I've created a simple diagram to illustrate the issue I'm currently facing. If you need the `mosquitto.conf` and client programs, let me know. The original intention was to distribute traffic, hence the current design.

It seems that Cadelo's HA Mosquitto involves directing traffic from the load balancer to a designated lead node, with other brokers set in follower mode. They synchronize data using their Cluster Management tool. In case the lead node fails, traffic is redirected to another node, addressing downtime but not achieving true load balancing.

Is it currently not possible for Mosquitto to implement Load Balancing functionality?

![image](https://github.com/eclipse/mosquitto/assets/56353753/f699259d-bf8e-400c-ad7f-9eb7b55cde64)

**Comment by win5923** [comment]
Hi @Daedaluz, thanks for your reply.

I've created a simple diagram to illustrate the issue I'm currently facing. If you need the `mosquitto.conf` and client programs, let me know. The original intention was to distribute traffic.

It seems that Cadelo's HA Mosquitto involves directing traffic from the load balancer to a designated lead node, with other brokers set in follower mode. They synchronize data using their Cluster Management tool. In case the lead node fails, traffic is redirected to another node, addressing downtime but not achieving true load balancing.

Is it currently not possible for Mosquitto to implement Load Balancing functionality? I saw that `HiveMQ` and `EMQX` both support Load Balancer, but I have not tested the scenario involving retained messages yet.

![image](https://github.com/eclipse/mosquitto/assets/56353753/dc7a08fb-02c7-4679-9d22-310cf817d62a)

**Comment by win5923** [comment]
apologize for the misunderstanding. I am using different clients for publishing and subscribing, with qos = 2. Regardless of whether the subscribe client reconnects or not, I always receive only half of the retained messages. I will try adjusting the parameters you provided. Thank you very much!

**Comment by ralight** [comment]
Closing this as complete, with a note that Cedalo will have a version that supports load balancing in the future.
