### ISSUE TITLE
mosquitto_loop possibly hanging on SSL

### ISSUE THREAD

**Issue by RaynoP** [eclipse/mosquitto#324]
Hi there,

I am new to the github community and have been playing around with the mosquitto library for a while now. It is not only teaching me the fundamentals of the library itself but also a bucket full of new C++ coding techniques.

I ran into an issue where the main loop is blocking the main function of my program for no reason. The only part of the source of the main loop function I can find that may be causing this is:

```
    if(mosq->sock != INVALID_SOCKET){
       if(FD_ISSET(mosq->sock, &readfds)){
#ifdef WITH_TLS
            if(mosq->want_connect){
                rc = mosquitto__socket_connect_tls(mosq);
                if(rc) return rc;
            }else
#endif
                {
                    do{
                        rc = mosquitto_loop_read(mosq, max_packets);
                        if(rc || mosq->sock == INVALID_SOCKET){
                            return rc;
                        }
                    }while(SSL_DATA_PENDING(mosq));
                }
            }

```
The SSL_DATA_PENDING code is ouside of the TLS compiler directive? Is this supposed to be? This is the only place in the code I can find that may be holding/blocking any other execution.

I have searched the internet flat trying to find some sample code on how to use the loop_read/write/misc functions to no avail. I see that FD_SET etc is required but my knowledge on winsock in this regard is very limited. Thus trying to use the select() function does not want to compile.

I also tried to convert the code to async/threaded but then none of my callbacks are ever called.

What am I missing?

Regards,
Rayno

**Comment by ralight** [comment]
SSL_DATA_PENDING() expands to just 0 if WITH_TLS is not set, so the do while loop will be executed just the once.

I suggest that people should use `mosquitto_loop_start()` or `mosquitto_loop_forever()` (non-blocking or blocking versions of the same thing) unless they particularly have a need to process the loop themselves - such as integrating with another network loop for example.

You need to call `mosquitto_loop_read()` whenever there is data available to read on the client socket. You call `mosquitto_loop_write()` when the client tells you there is data (using `mosquitto_want_write()`) and the socket is available to write. `mosquitto_loop_misc()` needs to be called every few seconds or so. It deals with sending PINGREQs to the broker if required.

If you're running your own threads, you need to use `mosquitto_threaded_set() to tell the library that you are doing so, otherwise it tries to optimise for the single threaded case.

**Comment by ralight** [comment]
There hasn't been any update on this for a while, so I'm closing it. If you still think there is an issue please reopen the issue and provide more information.
