### ISSUE TITLE
why mosquitto not support epoll?

### ISSUE THREAD

**Issue by liudf0716** [eclipse/mosquitto#449]
I have used mosquitto as broker to send control message to my mqtt client: [apfree wifidog](https://github.com/liudf0716/apfree_wifidog),
 however when clients reach to the number of tens of thousands , mosquitto's performance is bad: cpu reached 100% and mostly was sys time. I think that problem was caused by  mosquitto choosing poll/select mode, which has been proved it can  not support tens of thousand clients, but as a mqtt broker, that's a common scenario to support tens of thousand clients, so my suggestion is why not choose epoll mode? thanks！

**Comment by icraggs** [comment]
Just from a historical perspective, I will add that when an early draft of the MQTT specification was written, 50 simultaneously connected clients was described as a typical number!  MQTT and Mosquitto have been around for a number of years, and the typical expected behaviour changes over time.

**Comment by ralight** [comment]
Very simply - portability. The project will move to an event library in the future so we can get the best performance on all platforms.

**Comment by liudf0716** [comment]
@ralight libevent is portable too. so I don't think portability is the reason.
I think mosquitto project can use libevent as  its network  library, which is more professional in network area.

**Comment by ralight** [comment]
Honestly, I was there - portability was the reason.

Please don't confuse the situation as it appears now with the situation in 2009. At the time the project was started "nobody" had heard of MQTT. The Internet of Things wasn't a household name (the Eclipse Internet of Things project group was originally called Machine to Machine because in 2011 it wasn't clear which term was the best to use). Mosquitto was started as a fun project to implement this obscure protocol, perhaps for use in home automation. The idea that it would be used by companies such as Samsung and Deutsche Bahn would have been unbelievable. If the project had started out with that aim from the beginning then different decisions would have been made along the way.

**Comment by liudf0716** [comment]
@ralight 
As developer,  I can full understand that,  however, users does not  care what u choose, they only  know mosquitto can not support over tens of thousands clients but other mqtt broker can, such as [emqqt](https://github.com/emqtt/emqttd)

**Comment by ralight** [comment]
Well I can't argue with that. The difference between mosquitto and most other implementations is that mosquitto doesn't have a company behind it and so doesn't get the development resource. I'd like it to be otherwise, but that's the situation that exists.

**Comment by liudf0716** [comment]
@ralight please don't mind what I said.
I wish mosquitto to be more better, so gave my suggestion. mosquitto team has done their best, thanks.
