### ISSUE TITLE
CAfile required to start TLS listener

### ISSUE THREAD

**Issue by oej** [eclipse/mosquitto#517]
I just found out that a CAfile is required to start TLS listener. That does not really make sense. 

CAfile/CApath is needed when we have clients authorising with certs or have a bridge TLS connection, but not just to start a TLS listener. I would kindly propose that this is changed so that a TLS server can be enabled without a set of CA certificates that is not normally used to set up a TLS server only.

**Comment by ralight** [comment]
I'm sure you'll agree that all certificate based servers need a CA certificate (or are self signed, in which case they are their own CA certificate). cafile and capath are simply the means of configuring the CA files for your server. It is a deliberate decision to not include the entirety of CA certificates on the system in the configuration, it is up to the user to decide what is appropriate.

**Comment by oej** [comment]
No, I do not agree. In order to be a TLS SERVER, all you need is the server cert and the private key. The clients will have to have the CA cert to verify your server's certificate. This is the configuration that can't be done today.

If you require client certificates, that's another story and you then need a CA cert to verify the clients. That's pretty unusual, but a good use case.

If you are a client with outbound connections you need the CA cert to be able to verify, but then you do not need your own cert (unless the server requests client certs).

**Comment by Guzoft** [comment]
I agree with the OP @oej .

A broker listener that want's to identify itself with a TLS certificate, plus encrypt the data flow with the same certificate, doesn't logically need to know what Certificate Authority certifies the authenticity of it's own TLS certificate.

OTOH, a client connecting to the broker and wanting to verify that the broker is "who it says it is" will need access to at least one trusted Certificate Authority certificate authenticating the broker.


Of course, should the broker require the client(s) to identify with TLS certificate(s), **then** (and only then) the broker will need access to a Certificate Authority TLS certificate that authenticates the client's TLS certificate(s).

As a conclusion: If the Broker is configured to authenticate itself without requiring the client(s) to do the same, then the Broker should not need access to any CA certificate.

Could this Issue #517 please become approved (or in worst case, denied) so that we could know what to expect for this feature in a future release?

Regards

**Comment by schildbach** [comment]
I also think that a CA cert should not be required.

**Comment by ralight** [comment]
Changing this now would be a breaking change, so it could be considered for a 2.0 release, but not before.

**Comment by schildbach** [comment]
@ralight Why breaking? Configurations specifying CAfile would still work as before.

**Comment by xhpohanka** [comment]
This is definitely an issue. I'm now in situation (certificate generated by AWS) when I even do not have the CA certificate. I have had a hard time to even find that missing `cafile` or `capath`is responsible for connection errors because error message was not even mentioning it.

**Comment by mattdean-digicatapult** [comment]
I agree with others here, this is definitely an issue. I'm currently deploying a mosquitto container with ACME based certificates injected as a volume mount. Now because the ACME spec doesn't support retrieval of the root CA crt I basically have to ensure the right CA is installed on the mosquitto container and keep it up to date. This is entirely unnnecessary when all I'm after is an encrypted connection to the broker and not client auth.

Next @ralight the change here would I think only be a behavioural change for anybody wanting to provide a server TLS key and cert but not wanting TLS to be enabled (???). This seems like an unlikely issue to care about. Also per the documentation for `mosquitto.conf`:

> `cafile` `file path`
>
>  `cafile` is used to define the path to a file containing the PEM encoded CA certificates that are trusted when checking incoming client certificates. 
>
> `capath` `directory path`
>
>  `capath` is used to define a directory that contains PEM encoded CA certificates that are trusted when checking incoming client certificates. For capath to work correctly, the certificates files must have ".pem" as the file ending and you must run "openssl rehash <path to capath>" each time you add/remove a certificate. 

It would seem that the documented behaviour is that the cafile/capath is only used when checking for incoming client certificates. I honestly cannot see how this would not considered a bug, but please let me know if I'missing something.

**Comment by ralight** [comment]
@mattdean-digicatapult This behaviour changed in 2.0.0 back in December, it is only `certfile` and `keyfile` that are required now. I'm going to close this issue as fixed, please could you file a separate bug if it's not working for you.
