### ISSUE TITLE
some doubts

### ISSUE THREAD

**Issue by xiangjiangnan** [eclipse/mosquitto#571]
I have used mosquitto for a long time,I still have some doubts, why does not use windows Completion Ports and linux epoll to achieve high concurrency?I usually use mosquitto to test my client,so  I usually make some useless topics and it will be left in the mosquitto unless I restart the broker.What's more,  Is it  the compatibility and multi_function that has to make a balance when design a open source software ?If I just use this software in a fixed circumstance,whether can I have some changes?
Thanks.

**Comment by toast-uz** [comment]
Does #495 solve one of your doubts?

**Comment by xiangjiangnan** [comment]
@toast-uz Thanks,you have done so many on epoll!

**Comment by toast-uz** [comment]
Regarding Windows, a little more complicated. To begin with, on Windows, mosquitto has some restrictions and is not good at high concurrency operation.

Even except for the above constraints, I found very difficult that mosquitto got high concurrency on Windows.

I consider using libuv for mosquito. As you know, libuv is used in Node.js and provides common high concurrency framework regardless of kind of OS. Mosquitto has some common variables used around many parts of the source code, due to MQTT protocol stateful architecture. On the other hand, libuv provides event driven architecture maintains independence between events. Therefore, I could not rewrite mosquitto under libuv framework.

Does this comment answer for remaining of your doubts?

**Comment by xiangjiangnan** [comment]
@toast-uz  Thanks a lot.These days I read some source code.I find that mosquitto uses tree to manage all kinds of topics meanwhile uses hash table to manage every client's context.Tree is clear but query efficiency is bad when have more and more topics .Some regular topics may degenerate into linked lists if use tree to manage when I use mqtt client. (I use mqtt client for esp8266 ).So why not use hash table as well?

**Comment by toast-uz** [comment]
On develop branch, subscribed topics are managed by tree and hash table limited within each hierarchy. I am not sure of the intention because this implementation was made by @ralight .  But I guess it was due to ease of handling wildcard topic matching.

**Comment by toast-uz** [comment]
@xiangjiangnan did my comments help you? Close this issue if you are satisfied.

**Comment by toast-uz** [comment]
Closing. If you have any more question, post at mosquitto-dev ML.
