### ISSUE TITLE
ACL settings ineffective after SIGHUP

### ISSUE THREAD

**Issue by mosquser** [eclipse/mosquitto#588]
I have configured a mosquitto broker (version 1.4.14) with ACL (setting "acl_file" and "password_file" in /etc/mosquitto/conf.d/acl.conf). At first it is working as expected.

After I send a SIGHUP signal to the broker, all previously connected clients have full access to all topics. Also, any user can connect to the broker, even if not in the password_file.

According to the documentation (man 5 mosquitto.conf), these settings should be reloaded on SIGHUP:
acl_file:
> Reloaded on reload signal. The currently loaded ACLs will be freed and reloaded. Existing subscriptions will be affected after the reload.

password_file:
>Reloaded on reload signal. The currently loaded username and password data will be freed and reloaded. Clients that are already connected will not be affected.

**Comment by mosquser** [comment]
Solved this problem.
The permissions on the configuration files were insufficient for the user mosquitto. Apparently on initial startup the broker reads the configuration files before dropping privileges and thus with different permissions than on reload.
It would have helped a lot to have error messages on reload (like on startup if config file is not readable), but instead the broker just failed silently to read the files and accepted all connections.

**Comment by szarta** [comment]
Arguably, design-wise, I would expect Mosquitto to not read the configuration files as root, but it is a chicken and egg problem:  it needs to read the configuration to tell which user to downgrade to when it is running as root.  At the very least it seems like it should:

1. Read the config as root to determine what user to run as
2. Drop down to that user
3. Re-read the configuration as that user to reload the settings
4. On failure to read the config, abort due to permissions rather than continue with safe-defaults

4 is questionable - but if the configuration file is telling it where to log and the assumption is failures will log there and those aren't in line with the defaults, a poor administrator might be missing critical information (that there are permissions issues) as a result of permissions issues.

I am not sure how other daemons/servers do it (apache?  lighttpd?), but I can at least put in a pull request that does 1-4 and see if it gets accepted? =)

**Comment by mosquser** [comment]
Your suggested implementation would certainly have helped a lot in my case. Your 3rd point alone would have helped me find the problem faster.
My feeling is that doing point 4 as well is the best thing to do. I guess it is better not to run a service at all than to run it with a different configuration than expected.

**Comment by ralight** [comment]
I believe this has been fixed for a while now.
