### ISSUE TITLE
How do know if the device is online？

### ISSUE THREAD

**Issue by lauixData** [eclipse/mosquitto#622]
Is there a callback interface ?  Or other ways of getting it ?

**Comment by karlp** [comment]
you're missing a lot of context?  I'm going to _assume_ you mean, if you're some process A, that subscribes to some data, whether you can find out whether a client is connected to the broker?  The short answer is you can't, because that's what PUB/SUB is all about, separating those concerns.  However, you can very easily just publish to any given topic something application specific, and use wills to publish offlines, and process that with anything you like.  If you don't have anything that's an _issue_ it's probably best to ask such general questions on the mqtt mailing list.

**Comment by cjmaynard** [comment]
According to the [mosquitto-conf](https://mosquitto.org/man/mosquitto-conf-5.html) man page, you can enable notifications with 

    notifications true

This will allow you to receive state notification on the "`$SYS/broker/connection/<clientid>/state`" topic.  Unfortunately, if you're using a bridge, notifications are also sent across the bridge to the remote broker, which we find highly undesirable, so much so that we can't use this feature.  Of course if [`notifications_local_only`](https://github.com/eclipse/mosquitto/issues/233) were supported, that would be very useful.

Unless someone else has a better idea, the next best thing I came up with was to check the TCP connection state using [`netstat`](https://linux.die.net/man/8/netstat) or [`ss`](https://linux.die.net/man/8/ss).

**Comment by karlp** [comment]
@cjmaynard just use notifications_topic to set it to a topic that you're not bridging then.

**Comment by cjmaynard** [comment]
@karlp Specifying a `notifications_topic` doesn't help.  As far as I can tell, it makes no difference at all.

We want a local MQTT client to be able to get connection state notifications from the `"$SYS/broker/connection/<clientid>/state"` topic (or whatever topic that's specified by `notifications_topic`, it makes no difference).  This topic isn't bridged; yet when I set `notifications true`, we see the will topic of `"$SYS/broker/connection/<clientid>/state"` in the `CONNECT` message to the remote broker, followed by a `PUBLISH` message of the state, neither of which is desirable at all across the bridge.

I don't even understand what possible use these messages would  be across the bridge.  If the bridge is connected, we already know it and don't need that message; if it's not connected, the `PUBLISH` message will never get there, so what's the point?  Maybe there's a way to disable this though?  We just want notifications locally without a will topic set in the `CONNECT` message to the remote broker and without publishing the connection state across the bridge.  This is the behavior I had hoped to get by utilizing the `notifications_local_only` feature, but unfortunately it doesn't quite work right, as I previously indicated.

**Comment by karlp** [comment]
notifications and notifications_topic is only for bridges, and broker/connection/<BRIDGEID> is only for bridges too.

There's no tree of topics for every single client connected, and there never has been.

**Comment by cjmaynard** [comment]
Right.  I want to be able to locally monitor the state of the bridge connection, not client connections.  I just don't want any of those state notifications to be sent over the bridge to the remote broker, nor do I want the will topic to be set in the CONNECT message between brokers.

As I understand it, a client can subscribe to `"$SYS/broker/connection/<clientid>/state"` to get the desired state information about the bridge, but this requires `notifications true`, which has the highly undesirable side-affects I described.

My apologies if I'm not being clear or if I'm somehow not understanding your point.

**Comment by karlp** [comment]
@cjmaynard It sounds like you're purely interested in the notifications_local_only PR, and it seems like a bit of a hijack of this issue?

**Comment by cjmaynard** [comment]
@karlp I am interested in `notifications_local_only`, but it wasn't my intention to hijack this issue, as you say.  If you read my first response, I replied with information that I thought would help @lauixData.  I only brought up the issue because I don't think it's entirely obvious what the side-effects are of using `notifications true` actually are.  For me, they're so undesirable that I'm forced to use an ugly `netstat` hack instead, and in case this side-effect is equally undesirable to others, I thought I would mention a couple of possible alternatives.

I then continued commenting only after you wrote _"just use notifications_topic to set it to a topic that you're not bridging then."_ because I thought it should be made clear that the suggestion doesn't help anything.

If @lauixData doesn't care about the side-effects of `notifications true`, then go ahead and happily use it; otherwise something else is needed and I suggested some possible alternatives, although anyone is free to suggest something else.  Again, if my comments are being interpreted as somehow hijacking this issue, then I do apologize, as that was never my intention.  If you want, I can delete them all.

**Comment by lauixData** [comment]
@cjmaynard @karlp 

There is no good solution?
I see there are records in the log

```
# on-line
1512633831: New connection from 39.155.185.27 on port 1883.
1512633831: New client connected from 39.155.185.27 as MQTT_TEST (c1, k60, u'sanjin').

# disconnect
1512633835: Socket error on client MQTT_TEST, disconnecting.

```
Is there any way to get to disconnect and on-line notification ？？？

**Comment by edwin-oetelaar** [comment]
I think you need to read the manual on "the will".  If you subscribe to that, you get a notification when the device goes offline. If the device goes online, publish a message to the same topic, "online" and with "will" "offline" you can see the device status changing.

**Comment by PierreF** [comment]
@cjmaynard as @karlp said, notification and notification_topic is ONLY for bridge. This issue is not about bridge at all.
The original issue is about knowing if a device (an MQTT *client*, not a bridge) is connected or not.

@lauixData As suggested by @edwin-oetelaar, you need to track this information in your application and could use will message. Briefly you do:
* on connection, the device send an "I'm device $ID and i'm online" message
* just before (normal) disconnection, the device send a "I, device $ID, disconnecteed" message
* Set will, so that on abnormal disconnected (like network issue), the broker will generate a message on behalf of the device "I, device $ID, lost my connection".

Then, either using retained message or tracking this in your application state, keep the status of your devices.

Closing this ticket, as it's not an issue on Mosquitto but rather a question on MQTT. If you have further question on how to handle MQTT will message, could you please ask them on the [Mosquitto ML](https://dev.eclipse.org/mailman/listinfo/mosquitto-dev) or on the [MQTT ML](http://groups.google.com/group/mqtt)
