### ISSUE TITLE
I cant get mosquitto.service to work

### ISSUE THREAD

**Issue by Gabefire** [eclipse/mosquitto#628]
I changed the mosquitto.service file to the devel branch file and got this error. I'm running linux mint

● mosquitto.service - LSB: mosquitto MQTT v3.1 message broker
Loaded: error (Reason: Invalid argument)
Drop-In: /etc/systemd/system/mosquitto.service.d
└─override.conf
Active: inactive (dead)
Docs: man:systemd-sysv-generator(8)

Nov 22r 10:40:21 hqtt-Latitude-E6510 systemd[1]: mosquitto.service: Service has m
Nov 22 10:40:21 hqtt-Latitude-E6510 systemd[1]: mosquitto.service: Service has m
Nov 22 10:40:21 hqtt-Latitude-E6510 systemd[1]: mosquitto.service: Service has m

[Unit]
Description=Mosquitto MQTT v3.1/v3.1.1 Broker

[Service]
ExecStart=/usr/sbin/mosquitto -c /etc/mosquitto/mosquitto.conf
Restart=on-failure

[Install]
WantedBy=multi-user.target

**Comment by karlp** [comment]
Do you still need the old issue?

**Comment by Gabefire** [comment]
I closed it

**Comment by PierreF** [comment]
The full error message would be useful. If the full message is the same as in #627 ("Service has more than one ExecStart"), it's an issue in the SystemD service unit/SystemD configuration.

Since the pasted file seems only to have one ExecStart, that probably means you get multiple file merged in one. You should check SystemD documentation to check which files are merged to generate the non-working SystemD service unit.

AFAIK, SystemD will merge the following files:
* (/usr)/lib/systemd/system/mosquitto.service
* /etc/systemd/system/mosquitto.service
* /etc/systemd/system/mosquitto.service.d/*

Closing the issue as I don't see any Mosquitto issue but a SystemD miss configuration. If you have further indication that this is a Mosquitto issue, feel free to reopen.

If you need further help in configuring your SystemD startup script, please ask in [Mosquitto ML](https://dev.eclipse.org/mailman/listinfo/mosquitto-dev) or SystemD user group.
