### ISSUE TITLE
What is the singicance of calling _mosquitto_socket_nonblock if sock is blocking

### ISSUE THREAD

**Issue by zinahe** [eclipse/mosquitto#663]
While this code block is very understandable:
https://github.com/eclipse/mosquitto/blob/8de5ed446494e20aaeceebcfdde0b1969031f3c0/lib/net_mosq.c#L423-L429

**What about this** ? What is the singicance of calling `_mosquitto_socket_nonblock` if it is blocking ?
https://github.com/eclipse/mosquitto/blob/8de5ed446494e20aaeceebcfdde0b1969031f3c0/lib/net_mosq.c#L440-L446

**Comment by toast-uz** [comment]
Maybe one of them is wrong.
But, these codes already changed significantly on develop branch.

**Comment by zinahe** [comment]
@toast-uz,
Thanks for the response. But it seems that not much happened in this particular case, the code is still there in develop branch.
https://github.com/eclipse/mosquitto/blob/48dec391f75c40c944157be52e5ab7e0b2176230/lib/net_mosq.c#L370-L376

**Comment by toast-uz** [comment]
Thanks. Understood still there.

**Comment by zinahe** [comment]
I have posted the question on the **mosquitto-dev** ML, just in case. Let's see if someone responds.

**Comment by PierreF** [comment]
This is expected, the socket created by this internal function must always be a non-blocking socket.
However it is possible to block until the connection is established instead of being asynchronous. The "blocking" parameter does not refer to the socket being blocking or not, but if the function should wait (block) until the connection is established or return immediately and finish the connection later.

On the libmosquitto API side, this is reflected by mosquitto_connect vs mosquitto_connect_async function.

Hope this answer your question, if not and you have further feel free to reply on the ML or reopen this ticket.

**Comment by zinahe** [comment]
I see. Thank you for the explanation. So the raw socket is always running in non-blocking mode and the context of "blocking" parameter is only limited to as to how the initial connection is established. Gotcha !
