### ISSUE TITLE
Seqmentation fault starting mosquitto manually

### ISSUE THREAD

**Issue by gitjps** [eclipse/mosquitto#696]
I am using Raspberry 1 & Stretch and followed these [instructions](https://alexkychen.wordpress.com/2017/11/09/install-mosquitto-on-raspbian-stretch/).
```
pi@raspberrypi:~ $ mosquitto
Segmentation fault
pi@raspberrypi:~ $ mosquitto -c /etc/mosquitto/mosquitto.conf
Segmentation fault
```

**Comment by ralight** [comment]
Did you try installing with the first part of those instructions, i.e. 
```
wget http://repo.mosquitto.org/debian/mosquitto-repo.gpg.key
sudo apt-key add mosquitto-repo.gpg.key
cd /etc/apt/sources.list.d/
sudo wget http://repo.mosquitto.org/debian/mosquitto-stretch.list
sudo apt-get update
```
The issue that page was created for should be resolved, so the rest of it isn't necessary and is potentially dangerous.

**Comment by gitjps** [comment]
ok, thank for the advice

**Comment by Dan-in-CA** [comment]
Same problem here.

Following the initial instructions as Roger listed above and then:
sudo apt-get install mosquitto

After the install trying "systemctl status mosquitto" shows 
● mosquitto.service - Mosquitto MQTT Broker
   Loaded: loaded (/lib/systemd/system/mosquitto.service; enabled; vendor preset: enabled)
   Active: failed (Result: signal) since Fri 2018-02-16 10:14:49 PST; 2min 24s ago

Upon trying "mosquitto" on the command line returns:
Segmentation fault

**Comment by justinatomatic** [comment]
Same here 

I'm trying to get mosquitto running on a fresh install of Raspbian stretch on a Raspberry Pi Zero W.

I installed by apt-get after adding the debian stretch repo 
deb http://repo.mosquitto.org/debian stretch main

I didn't get any of the dependency problems that others are reporting in similar circumstances. 

But mosquitto isn't starting 

systemctl status mosquitto
yields
● mosquitto.service - LSB: mosquitto MQTT v3.1 message broker
   Loaded: loaded (/etc/init.d/mosquitto; generated; vendor preset: enabled)
   Active: active (exited) since Thu 2018-03-01 20:56:51 AEDT; 15min ago
     Docs: man:systemd-sysv-generator(8)
  Process: 255 ExecStart=/etc/init.d/mosquitto start (code=exited, status=0/SUCCESS)
   CGroup: /system.slice/mosquitto.service

manually starting via  ./mosquitto -c /etc/mosquitto/mosquitto.conf in bash shell gets
Segmentation fault
manually starting via  ./mosquitto -c /etc/mosquitto/mosquitto.conf in fish shell gets
fish: “./mosquitto v” terminated by signal SIGSEGV (Address boundary error)

**Comment by ralight** [comment]
Recent armhf builds haven't been built on a Pi since mine died. It seems as though the method I'm using isn't using the right build parameters, I'll see what I can do to fix it.

**Comment by justinatomatic** [comment]
Most appreciated, I've installed mosquito numerous times over the years on pi's, os x  and ubuntu VM's and never had a problem before.

**Comment by ianmaddocks** [comment]
Is there a solution to add Mosquitto to a RPi Zero? 
I've tried lots of suggestions, but a clean install extended with http://repo.mosquitto.org/debian/mosquitto-stretch.list still results in:

- systemd status: Active: active (exited) 
- manually running: Segmentation Error

Is the problem due to Raspbian Stretch?

**Comment by ralight** [comment]
This should hopefully be fixed soon (today/tomorrow) with a new version in the repository. It's been a bit of a nightmare getting a reliable working package build setup for the Pi 1.

**Comment by ianmaddocks** [comment]
@ralight just rushed a test and I can no longer find any mosquito packages. 

Screen trace:
pi@raspberrypi:/etc/apt/sources.list.d $ sudo wget http://repo.mosquitto.org/debian/mosquitto-stretch.list
--2018-04-09 08:14:19--  http://repo.mosquitto.org/debian/mosquitto-stretch.list
Resolving repo.mosquitto.org (repo.mosquitto.org)... 85.119.83.194, 2001:ba8:1f1:f271::2
Connecting to repo.mosquitto.org (repo.mosquitto.org)|85.119.83.194|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 50 [application/octet-stream]
Saving to: ‘mosquitto-stretch.list’

mosquitto-st 100%      50  --.-KB/s    in 0s       

2018-04-09 08:14:19 (957 KB/s) - ‘mosquitto-stretch.list’ saved [50/50]

pi@raspberrypi:/etc/apt/sources.list.d $ sudo apt-get install mosquitto mosquitto-clients
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package mosquitto
E: Unable to locate package mosquitto-clients
pi@raspberrypi:/etc/apt/sources.list.d $ ls -l
total 8
-rw-r--r-- 1 root root  50 Mar  4  2017 mosquitto-stretch.list
-rw-r--r-- 1 root root 195 Apr  9 08:07 raspi.list
pi@raspberrypi:/etc/apt/sources.list.d $ apt-cache search mosquitto
pi@raspberrypi:/etc/apt/sources.list.d $ 

This is my setup sequence from a new install:

wget http://repo.mosquitto.org/debian/mosquitto-repo.gpg.key
sudo apt-key add mosquitto-repo.gpg.key
apt-get update
apt-get upgrade
cd /etc/apt/sources.list.d/
sudo wget http://repo.mosquitto.org/debian/mosquitto-stretch.list
sudo apt-get install mosquitto mosquitto-clients

**Comment by justinatomatic** [comment]
Works for me

I did a  sudo apt-get update and on a pi zero that I had previously installed on mosquitto that wasn't working.

I did a sudo apt-get install mosquitto and that got mosquitto working but when I went to test it using the clients I realised I needed to upgrade the clients as well sudo apt-get install mosquitto-clients and it's all happy. 

Thanks for fixing this issue, most appreciated.

**Comment by ralight** [comment]
@ianmaddocks In your sequence from a new install you should do an apt-get update after you put mosquitto-stretch.list in your sources.list.d directory.

**Comment by ianmaddocks** [comment]
@ralight tested successfully via apt-get upgrade on prior install. Systemd say Mosquito.service is Active & Running. 
Thank very much for the fix and advice on apt-get update after sources.list.d change.

**Comment by ralight** [comment]
Excellent, glad you're all sorted, I'm going to close this now.
