### ISSUE TITLE
Unable to connect to IBM Watson IOT Platform or AWS IOT server using mosquitto_sub and mosquitto_pub C clients. 

### ISSUE THREAD

**Issue by Supriyaj29** [eclipse/mosquitto#787]
hi,

I am developing a client using mosquitto c client library api. It works fine with local mosquitto broker. However, when I use same client to connect/communicate with IBM Watson platform or AWS IoT server, none of my callbacks are called. From log it seem there are no acknowledgement received for connect, publish or subscribe. I am really not sure, where exactly is the issue.  I am using valid credentials (for IBM) and valid certificates for AWS. For AWS IOT dashboard does show attempted connection (number of connection count), but publish and subscribe does not work. Same works if used respective clients provided by AWS and IBM, which means there is nothing wrong with device creation or policy settings.

I also tried using mosquitto_pub and sub utilities to achieve the same, but no luck. Has anyone came across such issue before.  Am I missing anything here?

Any help would be appreciated.

**Comment by ralight** [comment]
Could this be an issue around TLS or server name indication (SNI) support? I would suggest trying with version 1.5 shortly.

**Comment by parthhappy** [comment]
This is the problem of certificate. Basicall you need 3 files.:
--cert *.pem   -> this file is the generated certificate. It has a certificate and a private key normally. But private key cannot be read by mosquitto here.
--key  *.pem   -> this file is the private key from your certificate. Since mosquitto cant read the private key from the certificate, you need to specify it here explicitly. Private key can be generated by OpenSSL using following command: openssl rsa -in cert.pem -out priv.pem where cert.pem is your certificate and priv.pem is your private key, which you specify here
--cafile  *.pem  -> last is the Root CA File which confirms the authenticity of the server. This Certificate can be downloaded from the server with the help of the Browser. In your case it is the AWS IOT page. Make sure that you download the root certificate.
This should normally work.

**Comment by ralight** [comment]
I think this has been answered above, so I'm closing this. If it is still a problem, please reopen and provide more details.
