### ISSUE TITLE
Cannot configure acl_file on a per-listener basis

### ISSUE THREAD

**Issue by jpflorijn** [eclipse/mosquitto#796]
According to the man page:
```
       per_listener_settings [ true | false ]
           If true, then authentication and access control settings will be controlled on a per-listener basis. The following
           options are affected:

           password_file, acl_file, psk_file, allow_anonymous, allow_zero_length_clientid, auth_plugin, auth_opt_*,
           auto_id_prefix.
```

So I wrote the following mosquitto.conf:
```
per_listener_settings true

listener 1883 localhost
acl_file first.acl

listener 1884 localhost
acl_file second.acl
```
and ran mosquitto against it, with the following result:
```
Error: Duplicate acl_file value in configuration.
Error found at mosquitto.conf:7.
Error: Unable to open configuration file.
```

I am running the current HEAD of the develop branch (`f2376551bc0a91368df3d3784aea2e3a3bf68bbf`).

Looking at `src/conf.c` I noticed the `acl_file` is not part of the per-listener settings. Is this an oversight? Or is it still to come?

**Comment by jpflorijn** [comment]
I've contributed a patch for this issue. Let me know if it needs anything else.

**Comment by ralight** [comment]
@jpflorijn Thanks for pointing this out, it was an oversight in as much as I'd done most of the work but not completed it or committed it. I've submitted a change that implements this. I really do appreciate the time you've taken on your PR, I haven't used it though because I'd already done a good deal of the work and for a very practical reason - it is problematic to take contributions at this point because the IP log of external contributions for this release has already been approved.

**Comment by jpflorijn** [comment]
@ralight So long as it gets fixed I'm happy. Thanks for looking into it!
