### ISSUE TITLE
Mosquitto TLS setup - accepts connections even without a CA.crt?

### ISSUE THREAD

**Issue by Electrobub** [eclipse/mosquitto#852]
Hello everyone,

I have setup a mosquitto server with the intentions of having it run only over TLS on port 8883 and open to clients as long as they have the CA.crt (no need for individual key pairs / authentication)

The Mosquitto config I am using is:
```
port 8883
cafile /etc/mosquitto/certs/ca.crt
keyfile /etc/mosquitto/certs/mosquitto.key
certfile /etc/mosquitto/certs/mosquitto.crt
```

I can connect to it using
**mosquitto_pub**
`mosquitto_pub -h 192.168.1.8 -p 8883 -t Server -m helloworld --cafile /etc/mosquitto/certs/ca.crt -V mqttv311`

And also with **Python (paho library)**
```
client = mqtt.Client("", True, None, mqtt.MQTTv311)
client.tls_set('/etc/mosquitto/certs/ca.crt')
client.connect("192.168.1.8",8883,60)
client.publish("debug", "Hello world!");
```

I have tested a few different things and found that they will only connect when the correct ca.crt file is used.

I have then tried connecting to it with an **ESP8266 (running Arduino)**
using 
WiFiClientSecure from ESP8266WiFi.h
and
the pubsublibrary from imroy

and it seems to connect without needing the ca.crt at all! (publishing and subscribing, no probs!)

Could somebody shed some light on this? (I assume the mosquitto server is not set up correctly to allow  TLS connections only or I mis-assumed something else?) I have tried testing this on multiple servers (local and remote) with changes in the certs and it works each time (while the other options get blocked)

**Comment by ptjm** [comment]
The client-side CA doesn't have  direct role in authentication. During the TLS handshake, your server will send mosquitto.crt to the client, and the client can choose to validate it, generally by verifying that the certificate has been signed using a known CA and that the certificate contains the expected information, usually in the form of the certificate commonName matching the requested host name. The server also needs to demonstrate that it has access to mosquitto.key. If the client chooses not to validate that certificate, and you're not using a client certificate, there's nothing to stop the connection from going forward. It will still be encrypted, but it will be susceptible to man-in-the-middle attacks. One could reasonably argue that it might as well not be encrypted since anyone in the position to eavesdrop is in a position to initiate a mitma.

In your case, the mosquitto tools are choosing not to trust the server connection if they don't have the appropriate CA. The other tools are choosing to proceed without validation.

**Comment by Electrobub** [comment]
Thanks for the detailed reply! It explains it clearly.

I had just found that the ESP wifi library does not automatically verify the CA

I will continue looking into how I can go about this using a custom CA on an IP (no domain name) (verify fingerprints maybe?)

If anyone is interested here is an example provided: https://github.com/esp8266/Arduino/blob/master/libraries/ESP8266WiFi/examples/HTTPSRequestCACert/HTTPSRequestCACert.ino  (it checks the commonName though)

**Comment by Electrobub** [comment]
I got this working, for anyone else interested: (time used by me, hopefully time saved by others ;) )

I updated the WiFiLibraries for ESP8266 (as the dev team has recently integrated BearSSL - can use that instead of AxSSL)

BearSSL can validate the certificate using the CA (as opposed to AxSSL)

Here is the basic outline of what needs to be done (with MQTT as well)
```
BearSSL::WiFiClientSecure espClient;
PubSubClient client(espClient);

BearSSLX509List cert(digicert);

setClock()

espClient.setTrustAnchors(&cert);
client.set_server(mqttServer, mqttPort);
client.connect(ID);
```
for more information, check out the example at: https://github.com/esp8266/Arduino/blob/master/libraries/ESP8266WiFi/examples/BearSSL_Validation/BearSSL_Validation.ino
