### ISSUE TITLE
Invalid user 

### ISSUE THREAD

**Issue by benuvelj** [eclipse/mosquitto#959]
Hi
I cross-compiled mosquitto broker for my MIPS platform. I copied all the below files to my target platform.
1. mosquitto_sub
2. mosquitto_pub
3. mosquitto
4. libmosquitto.so.1
5. mosquitto.conf

I tried executing as below
$ ./mosquitto -c mosquitto.conf.

Below is the error response I got after execution:
TEST-Target> ./mosquitto -c mosquitto.conf 
1536738760: mosquitto version 1.5.1 starting
1536738760: Config loaded from mosquitto.conf.
1536738760: Opening ipv6 listen socket on port 1883.
1536738760: Opening ipv4 listen socket on port 1883.
1536738760: Error: Invalid user 'mosquitto'.

For the simple subscription and publishing (within localhost ) should I change anything on mosquitto.conf file.

**Comment by fcarlier** [comment]
in mosquitto.conf : ```#user mosquitto > user mosquitto```

**Comment by ralight** [comment]
I think the others have covered this, but just to be very clear, if you run mosquitto as root, it will try and change to a less privileged user - by default `mosquitto`. The easy solution is to add the user mosquitto to your system, something like `adduser --system mosquitto` should do the job on some Linux systems. If you want mosquitto to run as a different user to this, use the configuration file option like `user benuvelj` instead. It is best to have a dedicated user for mosquitto though.

I'm going to close this because I think you have enough information now, but if you're still having problems please reopen and add some more details.
